### ISSUE TITLE
Environment variables support

### ISSUE THREAD

**Issue by juliencarnot** [Overv/openstreetmap-tile-server#1]
Thanks a lot for sharing! Do you intend to maintain this repo and make it an easy to deploy solution listed on switch2osm, or is it just an example?

I was looking for solutions to render and host tiles on a dockerized platform, alongside other containers (CMS, db, etc.). I see that some options are hard-coded (for example luxembourg region, geofabrik.de server...), couldn't they be set from [environment variables, that could be easily set in Docker compose](https://docs.docker.com/compose/environment-variables/)?

**Comment by Overv** [comment]
I definitely intend to maintain this repo, because I will be using it to host a production tile server very soon.

The Luxembourg region is not hardcoded, it is simply the default if you have not specified a region yourself as explained in the README.
