### ISSUE TITLE
 libgdal-dev issue

### ISSUE THREAD

**Issue by mkcisse** [Overv/openstreetmap-tile-server#100]
The following packages have unmet dependencies:
 libgdal-dev : Depends: default-libmysqlclient-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Overv** [comment]
Did you get this error when building the Docker image from scratch?

**Comment by mkcisse** [comment]
Yes, I used: make test

**Comment by mkcisse** [comment]
to correct this issue:
https://stackoverflow.com/questions/27100742/libmysqlclient-dev-installation-fails

**Comment by ausrasul** [comment]
Same thing here, @mkcisse solution didn't work or I didn't test properly.
Worth noting, I have an older commit from last year, that built correctly, now it doesn't build any more.
Probably something to do with ubuntu packages.

**Comment by pandel** [comment]
I already opened a pull request regarding this error.

https://github.com/Overv/openstreetmap-tile-server/pull/101
