### ISSUE TITLE
How can I keep data?

### ISSUE THREAD

**Issue by gabrielibis** [Overv/openstreetmap-tile-server#102]
I followed the steps in de readme file. The server works fine but when I reboot my sistem everything was losted. How can I keep server data?

**Comment by Overv** [comment]
You're going to need to be more specific. What exact steps did you follow and what data was lost?

**Comment by csandor** [comment]
I had the same issue, more specifically on a clean import I noticed that the container start postgresql12 instead of postgresql10 where the data volume is mounted. Maybe I'm wrong but I think it happens because of the Dockerfile line 65 installs the postgis package which now refers to postgresql12.

**Comment by rautex** [comment]
> 
> 
> You're going to need to be more specific. What exact steps did you follow and what data was lost?

i think hes talkiung about the imported data from psql

**Comment by csandor** [comment]
I commented here then deleted it as I had the same error and it was caused by my ignorance that this project was updated to posgtgres 12 and I used old docs that indicated postgres 10 directory for mounting the volume.

Well done guys and many thanks!
