### ISSUE TITLE
Update does not work

### ISSUE THREAD

**Issue by darekzbik** [Overv/openstreetmap-tile-server#103]
I try to run tile server on AWS EC2 machine. Server works correctly but autoupdate functionality does not work.

Further investigation of this issue shows that problem is related to the CRON server and lack of  CAP_AUDIT_CONTROL capability for the CRON. 

Docker containers started with Amazon EC2 docker installation does not have mentioned CAP_AUDIT_CONTROL permission. Probably others docker installation are also restrictive. I did not try but 99% that the same problem will happen for Amazon ECS (Amazon Elastic Container Service) which is using similar Amazon Linux distribution.

Lack of this capability (permission) cause a problem with [audit_setloginuid](https://linux.die.net/man/3/audit_setloginuid) call from [pam_loginuid](https://linux.die.net/man/8/pam_loginuid). This pam modules is used by ubuntu distribution for cron (`/etc/pam.d/crond`). This PAM module is nice for regular linux distribution, there is not much value in that in case of distribution running inside a container. 

Anyway possible options are:
1. Run docker with additional permissions by adding `--privileged` flag to a `docker run`. I try it as a workaround, it is working. In my opinion it is ugly to grant additional permission (not only CAP_AUDIT_CONTROL) to a container just to satisfy PAM configuration of CRON. I you think that it is a correct solution documentation should be updated
2. `pam_loginuid` module can be removed from `/etc/pam.d/crond` configuration so additional capability will be no longer required
3. `openstreetmap-tiles-update-expire` can be run periodically from a `run.sh` script without using CRON server. It will be required to prepare some script to run update every minute. 

Let me know what you think about it. I can prepare some solution as pull request.

If you would like to replicate this problem I took this image ami-071f4ce599deff521 (Amazon Linux AMI 2018.03.0.20191219.0 x86_64 HVM). Then docker was added:
```
yum -y install docker
/etc/init.d/docker start
usermod -a -G docker ec2-user
```

**Comment by darekzbik** [comment]
@Overv can you comment and suggest direction so I can work on the code and prepare PR

**Comment by Overv** [comment]
I would recommend that @stevo01 looks into it as he has contributed the auto-update implementation.

**Comment by nielsole** [comment]
Closing as there hasn't been any activity
