### ISSUE TITLE
RaspberryPi - armv7l - standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by lrnselfreliance** [Overv/openstreetmap-tile-server#111]
I'm unable to execute the initial import due to the following error:
> standard_init_linux.go:211: exec user process caused "exec format error"

After doing some searching, I believe this is caused by the Raspberry Pi's ARM architecture.  Here is the command I ran, and the full output:

```
docker run -v /tmp/luxembourg.osm.pbf:/data.osm.pbf -v openstreetmap-data:/var/lib/postgresql/12/main overv/openstreetmap-tile-server import
Unable to find image 'overv/openstreetmap-tile-server:latest' locally
latest: Pulling from overv/openstreetmap-tile-server
5c939e3a4d10: Pull complete 
c63719cdbe7a: Pull complete 
19a861ea6baf: Pull complete 
651c9d2d6c4f: Pull complete 
20d5d553b676: Pull complete 
03e39318cf30: Pull complete 
b7fae1a354e1: Pull complete 
83da7b9f3fcf: Pull complete 
2536976753b6: Pull complete 
ba76951a7d00: Pull complete 
dfa4f999acdb: Pull complete 
6f7275614a93: Pull complete 
3c4441f2a065: Pull complete 
5eb03131adc0: Pull complete 
bed5e015bdcf: Pull complete 
a58bd2cf1b53: Pull complete 
aa2529106d91: Pull complete 
6528d25f29e7: Pull complete 
044ceeb96bb4: Pull complete 
1367ff39094e: Pull complete 
5713a2ea5024: Pull complete 
a391bb1af664: Pull complete 
20205486ebb5: Pull complete 
bed9bee68297: Pull complete 
e3948dfc85c1: Pull complete 
Digest: sha256:0ecd80672de43aaedccf1bb42272a6f3ea3d4a6161184b6b8dc442cdd4d697d5
Status: Downloaded newer image for overv/openstreetmap-tile-server:latest
standard_init_linux.go:211: exec user process caused "exec format error"

```

I don't believe this is caused during the import, rather, before it.  If I run the container directly, it fails before complaining about a lack of import:
> $ docker run overv/openstreetmap-tile-server
> standard_init_linux.go:211: exec user process caused "exec format error"

Here is some information about my docker and machine:
> $ uname -a
> Linux raspberrypi 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux
> $ docker -v
> Docker version 19.03.4, build 9013bf5

If I'm correct, and this is an ARM architecture issue, is there any hope of getting an ARM version?  I'd be willing to do some of the work if someone could give me a head start.

Thanks for the great project!

**Comment by Istador** [comment]
Yes, the [docker image](https://hub.docker.com/r/overv/openstreetmap-tile-server/tags) is only build for `amd64` and not for `arm32v7` or any other architecture (`i386`, `arm64v8`, `ppc64le`, `s390x`, ...). And running the wrong architecture results in these kind of errors.

You could build the image yourself on your architecture with `docker build`.

There is also an docker feature to run other architectures with the `--platform` parameter. I'm not sure but I think it was experimental and needs enabling the experimental mode. You might also need to install [qemu-user-static](https://github.com/multiarch/qemu-user-static) for it to work.

I'm using that feature to build another project for other architectures [here](https://gitlab.com/Istador/gitlab-ci-orchestrator/-/blob/public/build.sh), but that's not the way to go. The future for multi arch builds is [buildx](https://docs.docker.com/buildx/working-with-buildx/).
