### ISSUE TITLE
Incorrect path in renderd config settings?

### ISSUE THREAD

**Issue by mympuk** [Overv/openstreetmap-tile-server#125]
/home/renderer/src/mod_tile/renderd.conf:
XML=/home/**renderaccount**/src/openstreetmap-carto/mapnik.xml
Path in image:
/home/**renderer**/src/openstreetmap-carto/mapnik.xml

**Comment by Istador** [comment]
Is the file in use?

[These lines](https://github.com/Overv/openstreetmap-tile-server/blob/cca2d00a78bdff152a915fba80131166cbb279bf/Dockerfile#L136-L139) are fixing it for the `/usr/local/etc/renderd.conf` file.

**Comment by mympuk** [comment]
Thanks for pointing!
