### ISSUE TITLE
Invalid reference format error when Setting up the server

### ISSUE THREAD

**Issue by chris442** [Overv/openstreetmap-tile-server#127]
Following the steps in the Readme file to set up the server, I have downloaded the osm.pbf file and stored it at location: 
_C:\Development\Uni\MSc project\mapdatazbritain-and-ireland-latest.osm.pbf_.

I then create the docker volume:
_docker volume create openstreetmap-data_

Then I have executed the command to import the data:  
_docker run -v 'C:\Development\Uni\MSc project\mapdata\britain-and-ireland-latest.osm.pbf':/data.osm.pbf -v openstreetmap-data:/var/lib/postgres/12/main overv/openstreetmap-tile-server import_

But I see the following error:

> C:\Program Files\Docker\Docker\resources\bin\docker.exe: invalid reference format.

**Comment by Istador** [comment]
Please try out different formats for your volume parameter, e.g.:
- `"C:\Development\Uni\MSc project\mapdata\britain-and-ireland-latest.osm.pbf"`
- `'C:\\Development\\Uni\\MSc project\\mapdata\\britain-and-ireland-latest.osm.pbf'`
- `'C:/Development/Uni/MSc project/mapdata/britain-and-ireland-latest.osm.pbf'`
- `'//C/Development/Uni/MSc project/mapdata/britain-and-ireland-latest.osm.pbf'`
- `'//c/Development/Uni/MSc project/mapdata/britain-and-ireland-latest.osm.pbf'`
- `'/C/Development/Uni/MSc project/mapdata/britain-and-ireland-latest.osm.pbf'`
- `'/c/Development/Uni/MSc project/mapdata/britain-and-ireland-latest.osm.pbf'`

If this doesn't help, also try out the extra slash after the colon:
- `//data.osm.pbf`
- `//var/lib/postgres/12/main`

Or put the file to a location without a space in it.

Docker volume mounts on windows are strange and a common issue.

**Comment by chris442** [comment]
Thanks, I tried all of the suggested combinations without any success until I tried removing the space however I'm now getting a different issue:

> 
> PS C:\Development\Uni> docker run -v C:\Development\Uni\MScProject\mapdata\britain-and-ireland-latest.osm.pbf:/data.osm.pbf -v openstreetmap-data:/var/lib/postgres/12/main overv/openstreetmap-tile-server import
> Unable to find image 'overv/openstreetmap-tile-server:latest' locally
> C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/overv/openstreetmap-tile-server/manifests/latest: unauthorized: incorrect username or password.

I've not had much experience using Docker before, do I need to create an image before executing that run command? The Readme file only mentioned creating a volume before this step.

**Comment by chris442** [comment]
Ah ignore that last update. I forgot I restarted the terminal after removing the space from the folder name and had to log back in to Docker. Thanks for your help @Istador
