### ISSUE TITLE
Prerendering option in import

### ISSUE THREAD

**Issue by mirzah** [Overv/openstreetmap-tile-server#143]
It would be great if import had an option like -e PRERENDER_LEVEL=15, so import would take much longer, but it would include creation of all tiles up to defined zoom level. That would enable (as far as I understand) hosting this container on much slower (=cheaper) servers.

**Comment by FritschAuctores** [comment]
See here: https://github.com/Overv/openstreetmap-tile-server/issues/15

Run `render_list --all` inside the container
