### ISSUE TITLE
Is there any way to use a custom style for the tiles?

### ISSUE THREAD

**Issue by ControlTheBit** [Overv/openstreetmap-tile-server#145]
As the title says :-)

Thanks for looking into it.

**Comment by saildeep** [comment]
I created a derived docker image for my fork of osm-carto like this:
`
FROM overv/openstreetmap-tile-server

RUN cd / \
 && git clone https://github.com/saildeep/openstreetmap-carto.git \
 && cd openstreetmap-carto \
 && git checkout transparency-no-labels \
 && carto project.mml > /home/renderer/src/openstreetmap-carto/mapnik.xml\`
Works for me

**Comment by 2803media** [comment]
@saildeep you only fork the overv/openstreetmap-tile-server repo and rm style folder and put yours instead?

I want to use the positron from cartodb and wan't find a way to do that!

https://github.com/CartoDB/basemap-styles/blob/master/cartocss/mobile-sdk-styles/positron/style.mss

Thanks for your help

**Comment by ControlTheBit** [comment]
Found a solution here: https://medium.com/illumination-curated/openstreetmap-tile-server-in-kubernetes-85bc571e48a3
