### ISSUE TITLE
Pre-Render?

### ISSUE THREAD

**Issue by gareth-johnstone** [Overv/openstreetmap-tile-server#15]
Is there a way to pre-render the tiles so they are not rendered on the fly?

**Comment by Overv** [comment]
The only way that I'm aware of is to write a script to query all tile images within a region. You can write a script in Python with `requests` and some loops, for example, to force all tiles to be rendered. This is how I've done it for my own website which requires the entire Netherlands region and it works fairly well.

**Comment by Istador** [comment]
Or you can use existing programs / scripts for that.

[render_list](https://www.volkerschatz.com/net/osm/render_list.html) (with `--all`) is already installed with mod_tile, which you feed by upper and lower x, y and z tile coordinates to render.

And [render_list_geo.pl](https://github.com/alx77/render_list_geo.pl) is very useful if you have geo coordinates instead of tile coordinates of your desired area (it's not already installed within the image so you have to insert/install it yourself).

Also interesting is [tile expiration](https://wiki.openstreetmap.org/wiki/Tile_expire_methods) to re-render existing tiles (e.g. in an productive environment). You can specify which zoom levels to re-render directly, or later when they are touched by a user.

**Comment by gareth-johnstone** [comment]
@Istador total noob question (im new to docker) how do i access render_list within the docker? (like where is its path) :)

**Comment by gareth-johnstone** [comment]
EDIT: kinda found it, but getting the following:

```
root@demo:/var/lib/docker/overlay2/1621bc07c2f86c269a1eb1ae2607549048074f9f57900ec6216ddde91ddd5f55/merged/home/renderer/src/mod_tile# ./render_list
ERROR: init_storage_backend: Failed to stat /var/lib/mod_tile with error: No such file or directory
Failed to initialise storage backend /var/lib/mod_tile

```

**Comment by Overv** [comment]
You want to go into the container instead of finding its file system on your local hard drive. Try the following while your container is running:

```
docker exec -it container-name-here bash
```

You will then be able to execute `render_list` from within the container itself where `/var/lib/mod_tile` does exist.

**Comment by gareth-johnstone** [comment]
> You want to go into the container instead of finding its file system on your local hard drive. Try the following while your container is running:
> 
> ```
> docker ps       <- get the container name
> docker exec -it container-name-here bash
> ```
> You will then be able to execute `render_list` from within the container itself where `/var/lib/mod_tile` does exist.

you sir, are a legend, thank you :)

**Comment by nielsole** [comment]
If you use render_list or render_list_geo, make sure to use `-m ajt` as that is the database name.

**Comment by dkhovanskii** [comment]
Hi everyone, I am using version v1.8.2 using the command:
docker run -d -e THREADS=24 -e "OSM2PGSQL_EXTRA_ARGS=-C 24000" --shm-size="512m" \
	--restart unless-stopped \
	-p 8080:80 --name osm -e ALLOW_CORS=enabled -e UPDATES=enabled \
	-v /home/data/osm/nodes:/nodes \
	-v /home/data/osm/data:/var/lib/postgresql/12/main \
	-v /home/data/osm/tiles:/var/lib/mod_tile \
	overv/openstreetmap-tile-server:v1.8.2 run
it starts fine but nothing rendered. I assumed that it is just to slow to render, but when I am trying to pre-render tiles using:
docker exec -it osm /bin/bash
then 
/usr/local/bin/render_list -m ajt -a -z 0 -Z 4 -n 24
it doesn't render anything (no files got created). the output looks like this:
root@358e72bb0bfc:/# /usr/local/bin/render_list -m ajt -a -z 0 -Z 4 -n 24
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
Rendering client
Starting 24 rendering threads
Rendering all tiles from zoom 0 to zoom 4
Rendering all tiles for zoom 0 from (0, 0) to (0, 0)
Rendering all tiles for zoom 1 from (0, 0) to (1, 1)
Rendering all tiles for zoom 2 from (0, 0) to (3, 3)
Rendering all tiles for zoom 3 from (0, 0) to (7, 7)
Rendering all tiles for zoom 4 from (0, 0) to (15, 15)
Waiting for rendering threads to finish
rendering failed with command 4, pausing.
rendering failed with command 4, pausing.
rendering failed with command 4, pausing.
rendering failed with command 4, pausing.
rendering failed with command 4, pausing.
rendering failed with command 4, pausing.
rendering failed with command 4, pausing.
rendering failed with command 4, pausing.

*****************************************************
*****************************************************
Total for all tiles rendered
Meta tiles rendered: Rendered 8 tiles in 10.00 seconds (0.80 tiles/s)
Total tiles rendered: Rendered 512 tiles in 10.00 seconds (51.18 tiles/s)
Total tiles handled: Rendered 8 tiles in 10.00 seconds (0.80 tiles/s)
*****************************************************
*****************************************************
*****************************************************

What am I doing wrong here?

**Comment by nielsole** [comment]
As you are likely unable to generate any tiles even on the fly this is unrelated to the issue. Nonetheless this is likely the step that failed: https://github.com/Overv/openstreetmap-tile-server/blob/master/run.sh#L85

**Comment by dkhovanskii** [comment]
Thank you very much for this hint @nielsole ! It was the issue. When I run then recreated a container it started to work.
