### ISSUE TITLE
Very slow rendering

### ISSUE THREAD

**Issue by gasparka** [Overv/openstreetmap-tile-server#151]
Zooming into new area may take well over 10 seconds to render the tiles. I have tried increasing the thread count and memory size, but it seems to really make no difference.
Pre-rendering all tiles is not an option for us.
I am wondering if there is something else to try?

**Comment by MaRaSu** [comment]
Common approach to pre-rendering is to render lower zoom levels (i.e. smaller zoom number) for the whole area your map covers and then possibly additionally selectively higher zoom levels for most popular areas. For example look at my fork at [openstreetmap-tile-server](https://github.com/MaRaSu/openstreetmap-tile-server) / pre_render.py.

You did not mention if it takes over 10 seconds to render new tiles at any zoom level. But usually the problem is lower zoom levels where PostGIS DB becomes the bottleneck. Higher zoom levels at e.g. 16-18 should render fast.

**Comment by gitrajeshr** [comment]
I am also finding the rendering is very slow when using the docker image compared to directly running the tile-server on Ubuntu 18/20. 
Any tuning /configuration suggested?

**Comment by RadekHavelka** [comment]
same problem here, I keep adding new and new indexes to make it work at least normal, but no success so far (with full planet import)

**Comment by RadekHavelka** [comment]
I see the roads procedure to run very sub-optimal:

```
EXPLAIN ANALYSE  SELECT *
 FROM high_road(545979, ST_SetSRID('BOX3D(1232776.392183985 6242153.477883983,1584998.218522266 6594375.304222265)'::box3d, 3857), 'kind!=''highway''')
;
                                                          QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------
 Function Scan on high_road  (cost=0.25..10.25 rows=1000 width=228) (actual time=1249987.743..1250001.211 rows=99590 loops=1)
 Planning Time: 28.549 ms
 Execution Time: 1250013.706 ms
(3 rows)

```
Not sure I am not missing some index. Can you maybe list indexes from your installs, or this command above to compare the numbers?

**Comment by Istador** [comment]
> Not sure I am not missing some index. Can you maybe list indexes from your installs, or this command above to compare the numbers?

The [indexes.sql](https://github.com/Overv/openstreetmap-tile-server/blob/7636079b4d04ceb21f37ec28b502c1a0c16f16b2/indexes.sql) (comming from [here](https://github.com/gravitystorm/openstreetmap-carto/blob/361886107f0423ca90c2f2648fb8bcb68141a0ba/indexes.sql)) is imported in the `run.sh`:
https://github.com/Overv/openstreetmap-tile-server/blob/7636079b4d04ceb21f37ec28b502c1a0c16f16b2/run.sh#L78-L79

**Comment by Istador** [comment]
And since you aren't using the default osm-carto style of this image, which doesn't even include a `high_road` function, you might want to repost that question on the project of that style you are using ([this](https://github.com/stamen/toner-carto)?).

**Comment by RadekHavelka** [comment]
Yes, I do have all the indexes from the .sql file, and added some more. But you are right, those functions are coming from other repo, I apologize. I will try to ask there (it is Toner repo, but not this one, some other modified to use osm2pqsql script. I guess the missing indexes are coming from this modification.

**Comment by Istador** [comment]
The indices from osm carto are chosen specifically to optimize the queries that the osm carto style is doing.

When someone is using another style or extending/modifying the queries of an existing style, those indices might need to be adjusted or extended by additional indices, some might even become obsolete.

**Comment by tajchert** [comment]
My times:

- Level 17, 3.5 seconds
- Level 16, 5 seconds
- Level 15, 18 seconds
- Level 14, 81 seconds
- Level 13, 231 seconds

(for the not prerendered area in a city)

Setup:
AWS t3a.large (8GB RAM, 2 vCPU cores), 80 GB EBS SSD drive.

Postgresql/style are a default one, docker:
```
version: "3"
    
services:
  osm_tiler:
    image: overv/openstreetmap-tile-server
    volumes:
      - openstreetmap-data:/var/lib/postgresql/12/main
      - $PWD/map-data/poland.poly:/data.poly
      - $PWD/map-data/poland-latest.osm.pbf:/data.osm.pbf
    ports:
      - "8080:80"
    command: "run"

volumes:
  openstreetmap-data:
    external: true
```

However my CPU usage never goes over 40% (disc doesn't seem to be a bottleneck) and there is a lot of time CPU is idle after receiving request to render.
```
2021-03-11T18:30:17.507664265Z renderd[138]: DEBUG: START TILE ajt 15 18224-18231 11104-11111, new metatile
2021-03-11T18:30:17.507682255Z renderd[138]: Rendering projected coordinates 15 18224 11104 -> 2250306.112717|6447616.209915 2260090.052337|6457400.149535 to a 8 x 8 tile
2021-03-11T18:30:35.127192661Z renderd[138]: DEBUG: DONE TILE ajt 15 18224-18231 11104-11111 in 17.619 seconds
```
CPU:
```
06:30:13 PM     CPU     %user     %nice   %system   %iowait    %steal     %idle
06:30:16 PM     all      1.51      0.00      0.50     97.49      0.50      0.00
06:30:17 PM     all      0.00      0.00      0.50     98.99      0.50      0.00
06:30:18 PM     all      1.49      0.00      0.99     95.54      1.49      0.50
06:30:19 PM     all      0.00      0.00      0.51     98.99      0.51      0.00
06:30:20 PM     all      0.50      0.00      0.50     98.99      0.00      0.00
06:30:21 PM     all      0.00      0.00      1.01     98.49      0.50      0.00
06:30:22 PM     all      1.00      0.00      1.00     98.01      0.00      0.00
06:30:23 PM     all      0.50      0.00      1.00     98.00      0.50      0.00
06:30:24 PM     all      0.50      0.00      1.49     97.51      0.50      0.00
06:30:25 PM     all      1.00      0.00      0.50     98.00      0.50      0.00
06:30:26 PM     all      1.00      0.00      1.00     97.50      0.50      0.00
06:30:27 PM     all      0.50      0.00      0.50     98.49      0.50      0.00
06:30:28 PM     all      4.48      0.00      1.00     94.03      0.50      0.00
06:30:29 PM     all      2.48      0.00      1.98     94.06      1.49      0.00
06:30:30 PM     all      1.01      0.00      0.51     90.91      0.51      7.07
06:30:31 PM     all      6.25      0.00      0.96     79.81     12.02      0.96
06:30:32 PM     all      1.50      0.00      0.50     96.50      1.50      0.00
06:30:33 PM     all     12.44      0.00      3.48     80.10      3.48      0.50
06:30:34 PM     all     39.70      0.00      2.01     53.77      4.52      0.00
06:30:35 PM     all     31.66      0.00      1.01     66.83      0.50      0.00
```

**Comment by stefanodecillis** [comment]
I'm facing the same problem here. it becomes really slow depending on the zoom level. 
In my case I increased the shared memory and the threads but it didn't get faster. Did you find a solution (or workaround) to this issue?

**Comment by tajchert** [comment]
I changed the provider to dedicated server with AMD 3600 and it seems to use 100% of threads correctly. It seems much more quick than AWS instance, but I didn't do a apples to apples benchmarks.

**Comment by RadekHavelka** [comment]
For me: I added quite a lot of new indexes, move them to separate PCI SSD card, so the data and indexes are not being read from the same device at the same time. Pre-rendered all levels 0-12, others are now fairly quick, altho some areas are sometimes "stuck" and takes longer to generate them

**Comment by Reygok** [comment]
I entered this thread, because the title said "Very slow" so I thought someone had the same problem as me, but no... I zoom into level 4, and it takes almost 2 minutes to render the tiles, and then still half of them stay gray and I have to zoom out- in so they appear. I have only Germany and Thailand imported. so like 90% of the world is blank, I really assumed this would be faster, and reading the comments here, I'm pretty sure it should.

I first did the import and run with the exact commands in the readme, then tried again with the options for more threads and more memory, no difference for both of them.

I'm running on a RHEL 7.9 VM, these are the specs:
Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
16 GB RAM

Anything that would explain this extreme slowness? Any more info needed from my side? Or should I make a new issue?

**Comment by nuutrum** [comment]
Take a look at: 
https://github.com/openmaptiles/openmaptiles
https://github.com/maptiler/tileserver-gl

You can download maps from http://download.geofabrik.de/.
We are using this on Rasperry Pi 3. Very fast and stable.

**Comment by devthejo** [comment]
> > Take a look at:
> > https://github.com/openmaptiles/openmaptiles
> > https://github.com/maptiler/tileserver-gl
> > You can download maps from http://download.geofabrik.de/.
> > We are using this on Rasperry Pi 3. Very fast and stable.
> 
> Please only take your time for this method, if you use it for a noncommercial purpose and or want to pay for their service.

On https://openmaptiles.org/about/
they claim "opensource and no-vendor lock-in", and after searching for a while, what I understand is you have to pay only for precompiled tiles packages with specific images data, like satellite views etc... But if you generate your own tiles, it's 100% free and open-source. It's seems like openstreetmap-tile-server to me. Tell me if I'm missing something.

**Comment by devthejo** [comment]
It' improving increasing threads using env (THREADS=24)

**Comment by devthejo** [comment]
I give also a a try to https://github.com/gravitystorm/openstreetmap-carto

**Comment by eveetc** [comment]
> @devthejo 

Wow ! Those are great news! Thank you!

How did you get the tileserver-gl working with the osm.pbf format ? 

`{ [Error: SQLITE_NOTADB: file is not a database] errno: 26, code: 'SQLITE_NOTADB' }
`

**Comment by devthejo** [comment]
@eveetc tileserver-gl works with mbtiles, you have to convert pbf files to mbtiles, openmaptiles provide opensource tools to do theses conversions yourself but this is long and teddious, they provide also ready to use mbtiles, but you can use them for free only if it's not for commercial purpose, and you have to pay if you want have an access to regular automatic updates, the conversion from pbf to mbtiles have a cost in CPU charge, so it's normal, when using pbf files, you do lazy calculation, so you can have latency at user request time, mbtiles files are precalculated tiles format, with fast serving for user, but need time to generate. You can do all the work yourself for conversion, or pay to have it done for you.
There is more explanations here: https://www.youtube.com/watch?v=GxnbLshM1iM
Hope it's helping :-)

**Comment by eveetc** [comment]
> @eveetc tileserver-gl works with mbtiles, you have to convert pbf files to mbtiles, openmaptiles provide opensource tools to do theses conversions yourself but this is long and teddious, they provide also ready to use mbtiles, but you can use them for free only if it's not for commercial purpose, and you have to pay if you want have an access to regular automatic updates, the conversion from pbf to mbtiles have a cost in CPU charge, so it's normal, when using pbf files, you do lazy calculation, so you can have latency at user request time, mbtiles files are precalculated tiles format, with fast serving for user, but need time to generate. You can do all the work yourself for conversion, or pay to have it done for you. There is more explanations here: https://www.youtube.com/watch?v=GxnbLshM1iM Hope it's helping :-)

Thank you so much! :) 
How could I have missed that....

Happy holidays! :)
