### ISSUE TITLE
Fonts added

### ISSUE THREAD

**Issue by RadekHavelka** [Overv/openstreetmap-tile-server#159]
Hi, while using this image mixed with Toner style, I realised the czech characters in czech area of the map are screwed due to missing font. I had to download "noto sans ui" from the web, put it into the container, now the text are ok again. Just in case anyone is having the same issue. apt-get installing noto sans package did not help, had to download the TTF files and put them to /usr/share/fonts , reset font cache and then rebuild all tiles (by clearing the tile cache volume)

**Comment by galewis2** [comment]
To be clear, is it this repo? https://github.com/stamen/toner-carto

**Comment by nielsole** [comment]
Hi, I am mimicking stalebot.
