### ISSUE TITLE
Question: How do you add more data into the database after setup?

### ISSUE THREAD

**Issue by MacaScull** [Overv/openstreetmap-tile-server#161]
Hello, 

Ive set up the tileserver through docker using a cyprus .osm.pbf file but now I want to add more, so I would like to add turkey in too.

Is there a simple docker command to do this or not?

**Comment by Istador** [comment]
See issue #110.

**Comment by MacaScull** [comment]
awesome thanks, you I will try merging .osm.pbf files together and them importing them.
