### ISSUE TITLE
Custom PostgreSQL config

### ISSUE THREAD

**Issue by tajchert** [Overv/openstreetmap-tile-server#170]
Hi,
Thanks for the awesome work.
Is there a way to configure custom PostreSQL parameters (default ones are for minimum hardware config)? Or does this require forking and creating a custom docker image?
[Currently used minimum PostgreSQL config](https://github.com/Overv/openstreetmap-tile-server/blob/bedff2a880bc829ca3ae4e9c67c9852e9f2f738f/postgresql.custom.conf.tmpl)
I want to change ex. `shared_buffers ` to more suited to my machine, seems obvious but I didn't find anything related to that in issues.

**Comment by Istador** [comment]
Just docker volume mount your own [postgresql.custom.conf.tmpl](https://github.com/Overv/openstreetmap-tile-server/blob/7636079b4d04ceb21f37ec28b502c1a0c16f16b2/postgresql.custom.conf.tmpl) to `/etc/postgresql/12/main/postgresql.custom.conf.tmpl`.

It'll be used here on each container start:
https://github.com/Overv/openstreetmap-tile-server/blob/7636079b4d04ceb21f37ec28b502c1a0c16f16b2/run.sh#L102
by using this function:
https://github.com/Overv/openstreetmap-tile-server/blob/7636079b4d04ceb21f37ec28b502c1a0c16f16b2/run.sh#L5-L9

**Comment by tajchert** [comment]
Thanks! Will try with next import!

**Comment by tajchert** [comment]
`docker run [...] -v ./myconfig.conf:/etc/postgresql/12/main/postgresql.custom.conf.tmpl [...]
`
Found as this is duplicate of #130
