### ISSUE TITLE
Prerendering tiles with render_list doesn't do anything

### ISSUE THREAD

**Issue by tajchert** [Overv/openstreetmap-tile-server#171]
Sorry if it is obvious or more related to `render_list` (or even my lack of docker knowledge) and not `openstreetmap-tile-server` itself.
I tried to pre-render 0-12 levels, opened bash for my docker instance, and put:
`render_list --num-threads=2 --min-zoom=0 --max-zoom=11 -a`
the output is as below, however it doesn't do anything (it just stays there, load on CPU is 0% and nothing is prerendered) instance is working fine (it renders tiles by URL requests).

`$ sudo docker exec -it 3ed1aa87d8c9 bash
root@xyz:/# render_list --num-threads=2 --min-zoom=0 --max-zoom=11 -a
debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile
Rendering client
Starting 2 rendering threads
Rendering all tiles from zoom 0 to zoom 11
Rendering all tiles for zoom 0 from (0, 0) to (0, 0)
Rendering all tiles for zoom 1 from (0, 0) to (1, 1)
Rendering all tiles for zoom 2 from (0, 0) to (3, 3)
Rendering all tiles for zoom 3 from (0, 0) to (7, 7)
Rendering all tiles for zoom 4 from (0, 0) to (15, 15)
Rendering all tiles for zoom 5 from (0, 0) to (31, 31)
Rendering all tiles for zoom 6 from (0, 0) to (63, 63)
`

**Comment by Istador** [comment]
As explained at https://github.com/Overv/openstreetmap-tile-server/issues/17#issuecomment-463381437, the `-m ajt` parameter is mandatory for this project.

**Comment by tajchert** [comment]
Oh, yes. It is working with that parameter. Thanks!
