### ISSUE TITLE
How to restart renderd?

### ISSUE THREAD

**Issue by EnGoPy** [Overv/openstreetmap-tile-server#174]
I try to edit scale (during container runtime) in `project.xml`  than convert it with carto into `mapnik.xml` but than I need to restart renderd (If I'm not wrong).
Actually I've found the way to restart `renderd` is to call `sudo /etc/init.d/renderd restart` but I cannot use that in this case. There is no `renderd` file in this directory.
Via `Dockerfile` I've found that file exists in directory `/home/renderer/src/mod_tile/` but when it's my directory and I run `./renderd restart` than I receive information "iniparser: cannot open /etc/renderd.conf".
Actually `renderd.conf` is placed in `/usr/local/etc/renderd.conf`

Is it good way to restart that service?
Maybe I'm calling wrong file in wrong direction?

**Comment by AramisN** [comment]
use this as a guide,
sudo -u renderer renderd -f -c /usr/local/etc/renderd.conf

no need to look for the run app, its already mentioned in the path.
