### ISSUE TITLE
Can't install shape files while building docker

### ISSUE THREAD

**Issue by patricerosay** [Overv/openstreetmap-tile-server#181]
Hi.
I used to be able to install the docker, but now, I'm running into the following issue: 
I'm downloading files from git
I execute the command "make test"

=>There's an error while downloading the file:

http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip

I've tried to upgrade manually the Dockerfile to the newest version openstreetmap-carto 5.3.1 without success so far.

Please advise.
P.

**Comment by Istador** [comment]
The external URL isn't available anymore and therefore it fails.

The newest carto version 5.3.1 [changed](https://github.com/gravitystorm/openstreetmap-carto/commit/396778b423853de4c3d2c0ad48a1f390e998ac49#diff-cea0c5554020ead8c74ea96861663b7c1a8cf4058ef9e9b0f2d58b8a38e1947a) the URL to use another source:
- https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip

But they also [changed the script name](https://github.com/gravitystorm/openstreetmap-carto/commit/67824003e02b27574de9b6f49313043248d5bcff#diff-40def9a8c3707b1957f5cec30f808df5518f7ae5528d681822a3abd9fb582d6d) that needs to be called with version 5.3.0  from `scripts/get-shapefiles.py` to `scripts/get-external-data.py`. So, that needs to be changed in the Dockerfile too:
https://github.com/Overv/openstreetmap-tile-server/blob/75e7714f200cf452bfbe2f249453125632773e48/Dockerfile#L130

**Comment by patricerosay** [comment]
Hi,
Thank you for your answer.
I tried that already.
Installed pip to get the python3’s package update to make the scripts/get-shapefiles.py run. But new errors are occurring.  
Traceback (most recent call last):
  File "./scripts/get-external-data.py", line 294, in <module>
    main()
  File "./scripts/get-external-data.py", line 192, in main
    psycopg2.connect(database=database,
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

The Postgres needs to be running and configured.

# ./scripts/get-external-data.py
Traceback (most recent call last):
  File "./scripts/get-external-data.py", line 294, in <module>
    main()
  File "./scripts/get-external-data.py", line 192, in main
    psycopg2.connect(database=database,
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "root" does not exist

Are you planning an update of your package ?

P.

**Comment by Istador** [comment]
Ah, ok, it needs the database running.
Then I'd suggest to not call it inside of the Dockerfile, but in the `run.sh` somewhere during the `import` command (probably after the first init block?):
https://github.com/Overv/openstreetmap-tile-server/blob/75e7714f200cf452bfbe2f249453125632773e48/run.sh#L36-L83

When you get it to work again with the new version, you can send in a [pull request](https://github.com/Overv/openstreetmap-tile-server/pulls) with your changes. @Overv will probably be happy to merge the fix.

---

There is already pull request #176 that tries to update `carto` to 5.3.1. But if the `get-external-data.py` needs access to the running database, then the PR should not work correctly.
