### ISSUE TITLE
re-render existing tiles after editing my own local database (no openstreetmap download/update)

### ISSUE THREAD

**Issue by ghost** [Overv/openstreetmap-tile-server#184]
hello,

I would like to re-render my tiles after making a small change to my own locale database. So I don't need an update from the openstreetmap servers.

I use the ready built openstreetmap-tile-server docker image.

Of course it would be best if only the tiles that are affected by the change in the database are rendered.
In a pinch, it would be sufficient for me if all tiles were simply recalculated, as my database is very small. 

Setting the environment variable UPDATE=enabled as described in the documentation would not help me, if I understood it correctly, as this only triggers an update from the openstreetmap servers.
after searching the issues, I came across the "Tile expire methods" and "render_list".

However, i don't know if this would be the right choice....

Can anyone tell me if you can trigger a simple re-render of the tiles and how to do that?

Thanks in advance

**Comment by Istador** [comment]
https://wiki.openstreetmap.org/wiki/Tile_expire_methods

You could provide the `render_expired` script the tile coordinates of the tiles that need re-rendering. It also [allows](http://rpm.pbone.net/manpage_idpl_32701225_numer_1_nazwa_render_expired.html) to mark tiles as dirty (so they are re-rendered on next access) or delete higher zoom levels.
If you don't have a list of the changes from the changes to your own osm db and want to re-render all existing rendered tiles, you could iterate over all existing files and extract the coordinates from the file path. 

With `render_list` (tile coordinates - complicated) or `render_list_geo.pl` (geo coordinates - easy) you can render specific zoom levels and geographic areas by specifying bounding boxes. There are multiple examples for it in many other issues, one of them: https://github.com/Overv/openstreetmap-tile-server/issues/17#issuecomment-463381437

You could also delete the rendered tiles in the file system yourself with `rm`. They'll automatically be rendered on the next access (I'd not suggest that for lower zoom levels, as rendering them takes some time, where your user has to wait for the image).

**Comment by rikardomarenzzi** [comment]
hello @Istador,

thank you very much for your answer

render_expired sounds like exactly what I need.

I followed https://wiki.openstreetmap.org/wiki/Tile_expire_methods and tried to generate a expire.list.

`root@9ca0f7187fa3:/# osm2pgsql -d gis -H localhost -U renderer -W renderer -S ~/osm2pgsql/default.style -P 5432 -s -C 800 -a master.osm.pbf -e15 -o expire.list
2021-05-07 15:09:13  osm2pgsql version 1.4.2
Password:
2021-05-07 15:09:17  Database version: 12.6 (Ubuntu 12.6-1.pgdg20.04+1)
2021-05-07 15:09:17  PostGIS version: 3.1
2021-05-07 15:09:17  ERROR: Cannot detect file format for 'renderer'. Try using -r.
root@9ca0f7187fa3:/# 
`
I copied the master.osm.pbf file (which i used for the import) into the folder in which I executed the command.
Is that that the right way or do I have to replace "diffs.osc.gz" with something else?

Am I correct in assuming that this command will generate a changefile based on the database and an import custom osm.pbf file?

What exactly do you mean by tiles coordinates? 
A geo bounding box consisting of latitude and longitude containing my changes?

Where exactly can I find the tile files if I want to delete them all at once?

Thanks again for your help

**Comment by Istador** [comment]
> render_expired sounds like exactly what I need.
> 
> I followed https://wiki.openstreetmap.org/wiki/Tile_expire_methods and tried to generate a expire.list.
> 
> `root@9ca0f7187fa3:/# osm2pgsql -d gis -H localhost -U renderer -W renderer -S ~/osm2pgsql/default.style -P 5432 -s -C 800 -a master.osm.pbf -e15 -o expire.list`
> [...]
> I copied the master.osm.pbf file (which i used for the import) into the container/folder in which I executed the command.
> Is that that the right way or do I have to replace "diffs.osc.gz" with something else?

I'm not sure if `render_expired` is what you want/need. I understood you, that updating your local database is already handled by you or some other software. You'd need to get the tile coordinates list from that process. Using osm2pgsql will update/overwrite the data in the database again.

> Am I correct in assuming that this command will generate a changefile based on the database and an import custom osm.pbf file?

`osm2pgsql` will do the import (append) directly to the database. With `-o expire.list` it spits out a list of tile coordinates that are affected by the process and that need to be invalidated/re-rendered.

That file'd then be the input for `render_expired`, so that `mod_tile`/`renderd` can either mark the cached files as dirty, delete them or re-render them.

Given that the database is already updated, I'd assume `osm2pgsql` to spit out an empty list? I don't know.

> What exactly do you mean by tiles coordinates?

Zoom level 0 has the 1 tile: 0/0/0
Zoom level 1 has the 4 tiles: 1/0/0, 1/0/1, 1/1/0 and 1/1/1
Zoom level 2 has the 16 tiles: 2/0/0, 2/0/1, 2/0/2, 2/0/3, 2/1/0, ...
It's a bit unintuitive because the same geographic area has totally different tile coordinates on different zoom levels.

> A geo bounding box consisting of latitude and longitude containing my changes?

Yes, you define an upper and lower longitude, an upper and lower latitude, which spans a rectantgular bounding box. Or in the case of `render_list` the same but, with tile coordinates.

> Where exactly can I find the tile files if I want to delete them all at once?

The rendered files should be stored inside the container under `/var/lib/mod_tile`. Probably you had set up a volume for that directory.

**Comment by rikardomarenzzi** [comment]
You have understood me correctly. The data in my database are changed by external software. 
However, no "tile coordinates list" is generated from this process. I would have to create this list by myself.
Currently, I only have a bounding box in which the change has taken place.
I should then be able to generate the tile coordinate list on the basis of the bounding box.

Is there a template for the "tiles coordinate list"?
What file format does the list need?

**Comment by Istador** [comment]
> Do you have a better idea?

If you want all tiles, for that rendered files exist:
```
find /var/lib/mod_tile -iname '*.png' | grep -Eo '[0-9]+/[0-9]+/[0-9]+' > expire.list

**Comment by rikardomarenzzi** [comment]
Hello @Istador,

now i have all the tiles in my expire.list that I want to rerender.

i tried this command:

`cat expire.list | /home/renderer/src/mod_tile/render_expired --map=osm --min-zoom=10 --delete-from=10 >/dev/null`

and I'm getting this response, but my changes are not visible. 

`root@924776ab0d47:/# cat expire.list | /home/renderer/src/mod_tile/render_expired --map=osm --min-zoom=10 --delete-from=10 >/dev/null`

`Rendering client`

`debug: init_storage_backend: initialising file storage backend at: /var/lib/mod_tile`

Am I using the command wrong?

**Comment by rikardomarenzzi** [comment]
I made a mistake with the render_expired command. I have now found the solution

Simply:

`cat expire.list | render_expired -m ajt`

The command is executed cleanly and all tiles re-renderd!

@Istador Thank you very much for your help.
