### ISSUE TITLE
Other styles

### ISSUE THREAD

**Issue by icemagno** [Overv/openstreetmap-tile-server#187]
Hi...

How can I use other styles? like these ones:

https://openmaptiles.org/styles/
https://github.com/openmaptiles/mapbox-studio-pencil.tm2

**Comment by rikardomarenzzi** [comment]
@icemagno could you find a way to apply new styles to the server?

Could any one give use a short description to apply/change the styles?
In #10 is written that we have just to replace the mapnik.xml... but how do i get a new one. Does anyone can supply a example file?

**Comment by astronautchen** [comment]
> @icemagno你能找到一种将新样式应用到服务器的方法吗？
> 
> 任何人都可以使用简短的描述来应用/更改样式吗？
> 在#10中写到我们只需要替换mapnik.xml...但是我如何获得一个新的。有人可以提供示例文件吗？

hello,do you have any ideals in this question~~

**Comment by nielsole** [comment]
There is a PR for this in progress https://github.com/Overv/openstreetmap-tile-server/pull/243/files
