### ISSUE TITLE
Loading Entire Planet File

### ISSUE THREAD

**Issue by bit-designer** [Overv/openstreetmap-tile-server#191]
I am looking for tips to troubleshoot the tile server loaded with the entire planet. 

Background:
- I am using a 2T hard drive
- I set up the docker container as follows (did not use flat nodes):

  `sudo docker run \
    -v $OSM_PBF:/data.osm.pbf \
    -v openstreetmap-data:/var/lib/postgresql/12/main \
    overv/openstreetmap-tile-server \
    import
  `
  
  `sudo docker run \
    -p 8080:80 \
    -v openstreetmap-data:/var/lib/postgresql/12/main \
    -d overv/openstreetmap-tile-server \
    run
  `

I tested this several times using a small PBF file (andorra-latest.osm.pbf). After verifying the process several times, I run with the planet-latest.osm.pbf file.

Result/Issue:
- The script ran for about a week (5 days), before alleviating my CPU (osm2pgsql and renderer had been using about 30%)
- I now have a docker volume of 1.4 T stored in /var/lib/docker/volumes/openstreetmap-data/_data/<volume ID>/
- I opened a browser to 'http://localhost:8080/tile/0/0/0.png', but nothing loading. After trying this and other tile coordinates several times I did get zoom level zero (0/0/0) to load once, but I never loaded again

Questions:
- Any tips on troubleshooting the server?
- Is there some way to verify the file in the docker volume?

Thank you in advance.

**Comment by davidveng** [comment]
Hello bitmstr
,
I'm having the same problem. Were you able to solve this?

Thanks

**Comment by davidveng** [comment]
> I am looking for tips to troubleshoot the tile server loaded with the entire planet.
> 
> Background:
> 
> * I am using a 2T hard drive
> * I set up the docker container as follows (did not use flat nodes):
>   `sudo docker run \ -v $OSM_PBF:/data.osm.pbf \ -v openstreetmap-data:/var/lib/postgresql/12/main \ overv/openstreetmap-tile-server \ import `
>   `sudo docker run \ -p 8080:80 \ -v openstreetmap-data:/var/lib/postgresql/12/main \ -d overv/openstreetmap-tile-server \ run `
> 
> I tested this several times using a small PBF file (andorra-latest.osm.pbf). After verifying the process several times, I run with the planet-latest.osm.pbf file.
> 
> Result/Issue:
> 
> * The script ran for about a week (5 days), before alleviating my CPU (osm2pgsql and renderer had been using about 30%)
> * I now have a docker volume of 1.4 T stored in /var/lib/docker/volumes/openstreetmap-data/_data//
> * I opened a browser to 'http://localhost:8080/tile/0/0/0.png', but nothing loading. After trying this and other tile coordinates several times I did get zoom level zero (0/0/0) to load once, but I never loaded again
> 
> Questions:
> 
> * Any tips on troubleshooting the server?
> * Is there some way to verify the file in the docker volume?
> 
> Thank you in advance.

Hello bitmstr,

I'm having the same problem. Were you able to solve this?

Thanks
