### ISSUE TITLE
I can't add 2 countries  (How can i bind 2 data with data.osm.pbf)

### ISSUE THREAD

**Issue by AnilKOC** [Overv/openstreetmap-tile-server#195]
Hello, i did good installation. But i want 2 countries. (Ukraine and Turkey)

I think i did mistake on binding datas with data.osm.pbf;
How can i bind 2 data with data.osm.pbf

Ukraine:

`docker run \
    -v /absolute/path/to/ukraine.osm.pbf:/data.osm.pbf \
    -v openstreetmap-data:/var/lib/postgresql/12/main \
    overv/openstreetmap-tile-server \
    import`

`docker run \
    -e DOWNLOAD_PBF=https://download.geofabrik.de/europe/ukraine-latest.osm.pbf \
    -e DOWNLOAD_POLY=https://download.geofabrik.de/europe/ukraine.poly \
    -v openstreetmap-data:/var/lib/postgresql/12/main \
    overv/openstreetmap-tile-server \
    import`

Turkey:
`docker run \
    -v /absolute/path/to/turkey.osm.pbf:/data.osm.pbf \
    -v openstreetmap-data:/var/lib/postgresql/12/main \
    overv/openstreetmap-tile-server \
    import`

`docker run \
    -e DOWNLOAD_PBF=https://download.geofabrik.de/europe/turkey-latest.osm.pbf \
    -e DOWNLOAD_POLY=https://download.geofabrik.de/europe/turkey.poly \
    -v openstreetmap-data:/var/lib/postgresql/12/main \
    overv/openstreetmap-tile-server \
    import`

**Comment by Istador** [comment]
The `import` command overrides/removes the already imported data in the database.

You either have to `merge` both pbf files into one pbf file that you `import` at once (prefered).

Or you need to use the `--append` command of `osm2pgsql` (it's orders of magnitude slower than merging and isn't exposed to the outside of the docker container).

See issue #110.
