### ISSUE TITLE
PreRendering?

### ISSUE THREAD

**Issue by meister-thron** [Overv/openstreetmap-tile-server#199]
Hello everybody,
I've a question. Is ist possible to pre-render tiles? For examle zoom from 1 to 10.

Thx for your effort!

**Comment by Overv** [comment]
Yes, by executing render_list inside the container. See https://github.com/Overv/openstreetmap-tile-server/issues/179

**Comment by meister-thron** [comment]
Thanks for your help. do not make sense of the code line. I can also post-render, e.g. 1 to 10 and then only 11. can someone show me an example? Many Thanks

**Comment by Istador** [comment]
```
# get running container id
c=$(docker ps | grep "overv/openstreetmap-tile-server" | grep -Eo "^[0-9a-f]+")

# render all tiles on zoom levels 0 to 10
docker exec -it "$c" render_list  -a  -f  -m ajt  -z 0  -Z 10

# render all tiles on zoom level 11
docker exec -it "$c" render_list  -a  -f  -m ajt  -z 11  -Z 11
```

Example with `docker-compose`: https://github.com/Overv/openstreetmap-tile-server/issues/18#issuecomment-466603283

Example for a specific region (`render_list` and `render_list_geo.pl`): https://github.com/Overv/openstreetmap-tile-server/issues/17#issuecomment-463381437
