### ISSUE TITLE
importing more then one pbf file

### ISSUE THREAD

**Issue by hugokoopmans** [Overv/openstreetmap-tile-server#20]
Seems I cannot import more then one pbf file?

Say I want to loaf Netherlands first and America second, if I run import more then once the data  in the second file is processed but never shown.

I have tried in two ways to do thiss.

First just run the import option twice once with pbf file a and second time with pbf file B, 
The map only shows data from file A.

Second I immport file A (the import statement als creates the database for the first time.
Then run the import command from the running tileserver, also no luck.

Both times there are no errors and the script finishes without error.

Is it not possible to load more then one pbf file using your script?

**Comment by dongjunson** [comment]
option -c is default setting. so i removed that. 
but continuously create the db. before db. 
you have to use option -a. 
this option is append the data into db created.

**Comment by cpina** [comment]
I've just had to do something like this. I've joined the opf before importing following this Q/A:
https://help.openstreetmap.org/questions/48843/merging-two-or-more-geographical-areas-to-import-two-or-more-osm-files-in-nominatim

I've done:
osmium merge country1.osm.pbf country2.osm.pbf -o together.osm.pbf.
