### ISSUE TITLE
Rerun without re-importing

### ISSUE THREAD

**Issue by bit-designer** [Overv/openstreetmap-tile-server#202]
Is there a way to rerun the tile server without re-importing the OSM data? I'd like to test various memory parameters without starting from scratch (entire planet import).

Thanks in advance!

**Comment by bit-designer** [comment]
The `run` command launches a (or some) processes on the container. It appears that rerunning (i.e. `run`) without stopping the processes does nothing:

```sh
docker: Error response from daemon: driver failed programming external connectivity on endpoint <container name> (<container ID>): Bind for 0.0.0.0:8080 failed: port is already allocated.
```

The "run" process can be killed. I used `kill -9 <PID>` using the PID from`docker container top <container name>`. However, this results in the whole container being killed. Maybe there is a way to restore it?

I'd love to find a work-around. Maybe there is a way load the previously imported database into a new container?

Open to ideas. I would think that there should be a clean way to do this.

**Comment by Overv** [comment]
Could you explain your problem? What is stopping you from running the `import` once and then just creating and destroying the container with `run` and different parameters?

**Comment by bit-designer** [comment]
@Overv, that works perfectly! I guess I made the assumption at some point (new to Docker and PostGIS databases) that the import was tied each to container instance. As you suggested, I can kill, stop, and/or remove the container and then rerun the server just fine without reimporting.

Thanks so much!
