### ISSUE TITLE
Docker import db error

### ISSUE THREAD

**Issue by letran3691** [Overv/openstreetmap-tile-server#203]
Hello everyone 
I've when import db via docker

I executed  command
```
docker run \
    -v /root/openstreetmap-tile-server/vietnam-latest.osm.pbf:/data.osm.pbf \
    -v openstreetmap-data:/var/lib/postgresql/12/main \
    overv/openstreetmap-tile-server \
    import
```

I seen  "Processing: Node(220k 220.0k/s) Way(0k 0.00k/s) Relation(0 0.0/s)2021-07-12 01:43:12  ERROR: PBF error: truncated data (EOF encountered)" in log return

I don't know this error,  had affect start server? 

![image](https://user-images.githubusercontent.com/19284401/125218558-7734af00-e2ed-11eb-98d1-70414709e13a.png)

**Comment by jpylypiw** [comment]
Normally the import process does not have any issues and works fine on a correct pbf file.
For me it seems like the pbf file is corrupted or maybe incomplete.

You can download the vietnam pbf file on the geofabrik website:
https://download.geofabrik.de/asia/vietnam.html

After downloading you can check the file using the md5 hash of the file:
https://download.geofabrik.de/asia/vietnam-latest.osm.pbf.md5

The command for a linux md5 hash of a file is `md5sum $FILENAME`.
I also recommend using the poly file for vietnam map. You also can download it on the geofabrik website:
https://download.geofabrik.de/asia/vietnam.poly
In the README.md file you can see how to use the file as volume.
