### ISSUE TITLE
Postgres Improvements

### ISSUE THREAD

**Issue by KoNEW** [Overv/openstreetmap-tile-server#206]
Hi, there

Nice project, but i have several questions and improvement proposals and want to discuss it. I am ready to make fork of project and to prepare pull-request, but just wanted to clarify some questions before start doing it.

1. Migration to PostgreSQL 13 - i am not very familiar with PostGIS/OSM compatibility notes, but underlying database have big performance improvements in major version and probably it would grant better performance

2. PostgreSQL configuration management. I have several ideas here:
- real life config tuning is hardly depends on underlying hardware - my propose to make default template adaptive based on actual hardware like choose shared_buffers to 25% of available RAM, random_page_cost based on disk type...
- it would be better to explicitly define in README volume mount pattern to change custom PostgreSQL configs
- i dislike current config split pattern - AUTOVACUUM defined as independent environment variable and other params defined in template file, it would be better to unify scheme
- there is a different recommendations for PostgreSQL configurations tuning for import/run scenarios - like disable fsync or increase maintanance_work_mem on import step

3. Add support for external database - it is really actual situation to use this image like scalable rendering/serving service, when persistence of data and performance would be provided by external database/tile cache storage

4. I propose to add naming prefix convention for used environment variable - current variable like THREADS/AUTOVACUUM etc is good when image used ASIS , but when it is deployed in big compose cascade or used with external system on configuration and shared env files, it can be confused cause names become not obvious for usage. For example we can use prefix like OSM_TS_ or TILE_SERVER_ that would produce better reading for variables in big system like TILE_SERVER_OSMPGSQL_THREADS

5. Also in real life - often situation when actual database should target several regions (for example - Germany and France). Currently image provides ability to mount data.osm.pbf file and also provide ability to download it with DOWNLOAD_PBF/POLY variables. It seems a little bit like semi-solution. And even more it use Luxembourg as default region and you can easy miss it during install process in log output if make some error. I have to proposal here:
- may be completely exclude DOWNLOAD_PBF from project for explicitly use external data files
- or add support for list of links in DOWNLOAD_PBF and combine them with osmconvert tools 
- NB: anyway i propose to remove default value for data file - i guess it would make image more predictable and opaque

What do you think about it?

**Comment by Overv** [comment]
I agree that the setup and parameters of the image could be designed better. Right now they grew more or less organically because there was initially no support for things like automatic updates and performance tuning. It is nice to support the option of having an external PostgreSQL database, but I don't think it should be the default since it requires the user to tune the database themselves. Ideally the image should help you import and serve data as fast as possible out of the box.

I think we should first gather input from the community to see what kind of extra features people would like to see so that we can make a design that fits all of these requirements before going out to make a huge PR.

**Comment by KoNEW** [comment]
Hi,

- I agree, by default it should use embedded version of database, but i guess that support for external instance can be added very organically
- Support for ability to change themes is excellent idea
- But default value for DOWNLOAD_PBF looks really unobvious for me 

You absolutely right, right now this image very simple out of the box, but looks not very suitable to use in production systems.

NB: For my own purpose i finished with splitting this docker image in independent images and gather them in docker-compose (postgis, tile-server, PBF importer). It also become transparent for monitoring cause i can create basic health-checks for each of modules.  I am not sure, but may be it also would be good way to evolve repo - split it in parts and provide some kind of combined image.

**Comment by alextroshin** [comment]
> NB: For my own purpose i finished with splitting this docker image in independent images and gather them in docker-compose (postgis, tile-server, PBF importer).

Hello! Can you share your results? I also want to do a similar splitting, but it seems too laborious

**Comment by nielsole** [comment]
Using an external database is also discussed here: https://github.com/Overv/openstreetmap-tile-server/issues/21

Supporting multiple pbf files is not planned, although we need to document how to merge them ahead of time as this is an often requested feature. 

> the ability to choose many more themes out of the box

This by now has a separate ticket also: https://github.com/Overv/openstreetmap-tile-server/issues/290

> but looks not very suitable to use in production systems

That's fine. This repo very much aims to be a quickstart. 

> But default value for DOWNLOAD_PBF looks really unobvious for me

Hmmm maybe, i have never accidentally run into this flag.

> naming prefix convention for used environment variable 

Changing existing variable names breaks compatibility, so this would still need to fall back on the old ones

> Migration to PostgreSQL 13

I think we did that by now

> it would be better to explicitly define in README volume mount pattern to change custom PostgreSQL configs

Someone who is this involved might just as well build on top of this repo and simply overwrite the default config

> PostgreSQL configuration management

I think postgres works well enough out of the box. Any PR with a custom config would probably need to show it's performance improvements to be merged. I don't think this is required at the moment.
