### ISSUE TITLE
update-tiles-expire make DBNAME configurable

### ISSUE THREAD

**Issue by robjuz** [Overv/openstreetmap-tile-server#208]
I'm working on a Kubernetes deployment of this image and face the problem that the database name is hardcoded

Could you change DBNAME=gis to DBNAME=${DBNAME:-gis}

This simple change will not break you code and enable me to use an external database

**Comment by Istador** [comment]
As far as I see, this at least requires changes in the `run.sh` ([1](https://github.com/Overv/openstreetmap-tile-server/blob/7b82bcae9dd067cbfd3a59371982e3b072acace2/run.sh#L37-L41) and [2](https://github.com/Overv/openstreetmap-tile-server/blob/7b82bcae9dd067cbfd3a59371982e3b072acace2/run.sh#L75-L79)), [openstreetmap-tiles-update-expire](https://github.com/Overv/openstreetmap-tile-server/blob/7b82bcae9dd067cbfd3a59371982e3b072acace2/openstreetmap-tiles-update-expire#L24) and in the [project.mml](https://github.com/gravitystorm/openstreetmap-carto/blob/eed4caf61934d721e559cdb4d7944810ac0cf750/project.mml#L29) before compiling it in the [Dockerfile](https://github.com/Overv/openstreetmap-tile-server/blob/7b82bcae9dd067cbfd3a59371982e3b072acace2/Dockerfile#L135).

**Comment by galewis2** [comment]
I think changing the dbname is probably the easiest solution given the hardcoding in the style.
