### ISSUE TITLE
$WGET_ARGS

### ISSUE THREAD

**Issue by exussum12** [Overv/openstreetmap-tile-server#210]
This is not documented and errors show up due to it.

example

wget "" https://google.com -O /dev/null
http://: Invalid host name.

I was going to remove the quotes but as its not documented, not sure whats best, remove the option or add docs ?

**Comment by Istador** [comment]
Introduced here: https://github.com/Overv/openstreetmap-tile-server/commit/953232051f6407fff8fd711fed86edc3e43d56de

I think the quotes should be removed, so just a plain `$WGET_ARGS` instead of `"$WGET_ARGS"`.
