### ISSUE TITLE
Issue running on Azure container

### ISSUE THREAD

**Issue by uberEpicDonkey** [Overv/openstreetmap-tile-server#216]
Hi,
I'm trying to get this up and running on Azure. It works fine locally on docker desktop, but as soon as I try to spin it up on Azure it breaks down with the following: 
`Error: Failed to start container osmsetup, Error response: to create containerd task: failed to create container {containerid}: guest RPC failure: failed to create container: failed to run runc create/exec call for container {containerid} with container_linux.go:349: starting container process caused "exec: \"import\": executable file not found in $PATH": exit status 1: unknown`

Do anyone have an idea as to why this could happen?

**Comment by Istador** [comment]
Looks like it tries to execute `import` instead of `/run.sh import`.

What command or configuration do you use to create/start it?

```
az container create ... --command-line "/run.sh import"
```

https://docs.microsoft.com/en-us/azure/container-instances/container-instances-start-command
https://docs.docker.com/engine/reference/builder/#cmd

**Comment by uberEpicDonkey** [comment]
Thanks for the prompt reply. Yeah, I agree it seems like it's something down that path.

I have docker desktop and use the integration towards azure. Here is the command I'm using:

`docker run --name osmsetup -e UPDATES=enabled -e DOWNLOAD_PBF=https://download.geofabrik.de/europe/denmark-latest.osm.pbf -e DOWNLOAD_POLY=https://download.geofabrik.de/europe/denmark.poly -v osmdata/osm-data:/var/lib/postgresql/12/main -v osmdata/osm-rendered-tiles:/var/lib/mod_tile overv/openstreetmap-tile-server input`

**Comment by uberEpicDonkey** [comment]
If I don't add the input parameter, it will stop, as expected, on the: How to use provide either run or input instructions.
If I add the parameter as above, it will try to execute input and not provide it as a parameter.

**Comment by Istador** [comment]
It's `import` not `input`.

If I understand it correclty, the [azure integration](https://docs.docker.com/cloud/aci-integration/) lets you execute docker commands on your local machine, which will cause it to start things in the azure cloud after using `docker context use ...`. Likely there goes something wrong at translating the entrypoint/command correctly to the azure format behind the scenes? Try unsetting the entrypoint and provide it manually:

 `docker run --name osmsetup -e UPDATES=enabled -e DOWNLOAD_PBF=https://download.geofabrik.de/europe/denmark-latest.osm.pbf -e DOWNLOAD_POLY=https://download.geofabrik.de/europe/denmark.poly -v osmdata/osm-data:/var/lib/postgresql/12/main -v osmdata/osm-rendered-tiles:/var/lib/mod_tile --entrypoint="" overv/openstreetmap-tile-server /run.sh import`

I don't use Docker Desktop, Windows nor Azure, so I'm no expert on this but am just guessing.

**Comment by uberEpicDonkey** [comment]
Thanks for pointing out the obvious with input! Somehow along my trial and error I wrongly replaced import with input. :-)

I got further now with: 
`docker run --name osmsetup2 -e UPDATES=enabled -e DOWNLOAD_PBF=https://download.geofabrik.de/europe/denmark-latest.osm.pbf -e DOWNLOAD_POLY=https://download.geofabrik.de/europe/denmark.poly -v osmdata/osm-data:/var/lib/postgresql/12/main -v osmdata/osm-rendered-tiles:/var/lib/mod_tile overv/openstreetmap-tile-server /run.sh import` adding the /run.sh was the key it seems. --entrypoint="" doesn't seem to be needed. Now i just have to figure out some permission issues. Thanks again!

**Comment by Istador** [comment]
Yes, the `--entrypoint=""` was more as a common baseline. Without it, if you'd try to run the command locally without azure, it might fail because it'd try to call `/run.sh /run.sh import`.

**Comment by uberEpicDonkey** [comment]
You are probably right.
For future reference, if anyone else might want to set this up on Azure Container Instances, you can't. The only way to mount volumes in ACI is through Azure File Share, which doesn't allow postgress to create the links and user it wants to. So setup will fail. Alternative is setting it up in Azure Kubernetes Service which supports dynamic diks and persistant storage or setting up an VM instead.
