### ISSUE TITLE
Error during import without internet access

### ISSUE THREAD

**Issue by nicopadu** [Overv/openstreetmap-tile-server#221]
Actually running this server in an environment without internet access.

But during Docker Build stage, we have internet. Then at this point we extend Docker image to download locally our intended data file. Something like the following:

```
FROM overv/openstreetmap-tile-server:v1.7.4
RUN wget "http://download.geofabrik.de/asia/gcc-states-latest.osm.pbf" -O /data.osm.pbf
COPY startup.sh /
ENTRYPOINT ["/startup.sh"]
```
our `startup.sh` script just checks if we need to run `./run.sh import` before finally executing `./run.sh run`

All works in our local machine - as usual :)

The issue is when running this initialization process without internet...
There is a point in run.sh that fetches external data and we fail there:
```
#Import external data
sudo chown -R renderer: /home/renderer/src
sudo -u renderer python3 /home/renderer/src/openstreetmap-carto/scripts/get-external-data.py -c /home/renderer/src/openstreetmap-carto/external-data.yml -D /home/renderer/src/openstreetmap-carto/data
```

Error message during import: 
```
...
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='osmdata.openstreetmap.de', port=443): Max retries exceeded with url: /download/simplified-water-polygons-split-3857.zip
```

And then while running server: 
```
An error occurred while loading the map layer 'ajt': Postgis Plugin: ERROR:  relation "icesheet_polygons" does not exist
LINE 1: SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "...
```

**Questions:**
* is there an elegant way to do not depend from internet to execute `run.sh import` ?
* what could be the consequences of skipping execution of `get-external-data.py` completely?
* is there a way to configure `external-data.yml` to look for files locally (previously downloaded)?

Note: running `run.sh import` during docker build stage causes our docker file to be > 12Gb - not a good idea.

Thanks for any feedback!

**Comment by MKaczkow** [comment]
I had similar issue - only difference is I tried to manually build server. You can modify `get-external-data.py` to unzip previously downloaded files instead of downloading them. Something like this: 

https://controlc.com/0fc1557f

I guess you should also modify/ add mounting downloaded files in Dockerfile - though I am not by any means Docker expert
