### ISSUE TITLE
/usr/bin/openstreetmap-tiles-update-expire: 12: cd: can't cd to /home/renderer/src/mod_tile/

### ISSUE THREAD

**Issue by mpele** [Overv/openstreetmap-tile-server#222]
Updating doesn't work. During import the message is show:

```
+ sudo -u renderer openstreetmap-tiles-update-expire 2021-10-29
/usr/bin/openstreetmap-tiles-update-expire: 12: cd: can't cd to /home/renderer/src/mod_tile/
```
The same error is shown and during manual start of the command. 
Also, I can confirm that folder mod_tile doesn't exist in /home/renderer/src/  .

**Comment by AndrewBedscastle** [comment]
Same issue here
I'd say it is quite clear (given my very little experience with Dockerfiles)

Until 1.7.4 mod_tile was cloned from github

`RUN mkdir -p /home/renderer/src \
 && cd /home/renderer/src \
 && git clone -b switch2osm https://github.com/SomeoneElseOSM/mod_tile.git --depth 1 \`

As of 1.8.0 it is installed differently which leads to /home/renderer/src/mod_tile no longer existing

**Comment by Istador** [comment]
The directory was removed with #214 for [v1.8.0](https://github.com/Overv/openstreetmap-tile-server/releases/tag/v1.8.0) to reduce the image size.

---

`osmosis-db_replag` seems to be the only local reference used in that directory.

https://github.com/Overv/openstreetmap-tile-server/blob/1e684edb6af361d71c6ba5dcf2698c3e1d5ba282/openstreetmap-tiles-update-expire#L142

Possible solution: copy `osmosis-db_replag` and remove the `cd` and the `.` in the `$PATH` change (the `$ACCOUNT` is used once later again, but could be hardcoded instead)?

```
COPY  --from=compiler-modtile-renderd  /root/mod_tile/osmosis-db_replag  /usr/bin/osmosis-db_replag
```

https://github.com/Overv/openstreetmap-tile-server/blob/1e684edb6af361d71c6ba5dcf2698c3e1d5ba282/openstreetmap-tiles-update-expire#L5-L12

**Comment by Overv** [comment]
It looks like that does the trick, yeah.

**Comment by mpele** [comment]
It looks like that everything is not yet as it should be.
The script starts but doesn't finish everything.

```
root@ed2175e22948:/var/lib/mod_tile# openstreetmap-tiles-update-expire 
Error connecting to database: FATAL:  role "root" does not exist

rm: cannot remove '/var/lib/mod_tile/dirty_tiles.787': No such file or directory
```

**Comment by mpele** [comment]
Sorry, it works. 
I was logged in as root, not as renderer.
