### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by maxim22m** [Overv/openstreetmap-tile-server#223]
Hi there.
I'm ran a self hosted OSM tile server with this repo. map is working well and functional and accessible with leaflet demo.
when I use tile map link ( http://map.company.org:8080/tile/{z}/{x}/{y}.png) for serving tiles in [Kibana ](https://www.elastic.co/de/kibana/)map, no tile loaded and browser console print below error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://map.company.org:8080/tile/65535/65536/17.png. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)

I'm digging issues and forums and trying almost all tips and problem is not solved. some of tips:

>         - add ALLOW_CORS=enabled flag when running docker that add "Header set Access-Control-Allow-Origin "*"" into apache conf.
>         - put map server behind reverse proxy and manipulate headers with nginx and dd some headers like this:
>                add_header 'Access-Control-Allow-Origin' '*' always;
>                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
>                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
>                add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
>         - change kibana CORS settings; server.cors.enabled.
>         - tiles can be downloded in browser without any problem and 'Access-Control-Allow-Origin' '*' is exist in headers.
>         and etc ... .

this problem is belong to kibana or OSM?
I'm so confused and glad to be get help with you, thanks.

OSM version: latest (just download past week)
Kibana version: 7.15.1

**Comment by Istador** [comment]
I'm not sure what and how Kibana is involved in your situation, but the image of this project does look for a `ALLOW_CORS` environment variable that you can set to `enabled`. See the readme:
https://github.com/Overv/openstreetmap-tile-server/blob/705237446adacea44302692c8dfb0405dbfb2abd/README.md#L104-L115

This will influence the `apache` service inside of the docker container. If this doesn't work and you have a reverse proxy running infront of the OSM container that doesn't forward or does overwrites the header set by the container's `apache`, you likely need to configure the option in the proxy too.

**Comment by maxim22m** [comment]
> 
> 
> I'm not sure how Kibana is involved in your situation, but the image of this project does look for a `ALLOW_CORS` environment variable that you can set to `enabled`. See the readme:
> 
> https://github.com/Overv/openstreetmap-tile-server/blob/705237446adacea44302692c8dfb0405dbfb2abd/README.md#L104-L115
> 
> This will influence the `apache` service inside of the docker container. If this doesn't work and you have a reverse proxy running infront of the OSM container that doesn't forward or does overwrites the header set by the container's `apache`, you likely need to configure the option in the proxy too.

thanks,
the problem solved automatically, but I'm guessing its because of prerender processes. after prerendering complete, problem is disappeared and working well.
