### ISSUE TITLE
How to edit name of a place?

### ISSUE THREAD

**Issue by maxim22m** [Overv/openstreetmap-tile-server#226]
Hi again;

for editing name of a place, what things we must do?
I find osm_id of a place and select it on PostgreSQL (_planet_osm_rels table_) and edit that's name in tag then prerender bbox of it in multi level of zooms, but nothing is changed in map frontend.
is it related to mapnik.xml?
or I'm guessing wrong and this issue must be questioned in openstreetmap main repo?

**Comment by Istador** [comment]
If it's a name correction that applies to anywhere in the world (e.g. the name of a street changed), which should apply to every OSM instance in the world, then that change should be done on https://openstreetmap.org

---

And if you only want to replace the name in your own local OSM instance:

If I remember correctly the osm-carto [style](https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml) by default uses the names from dedicated `name` columns in the tables and not from the `name` tag inside of the `tags` JSON data. Assuming you have the right `osm_id`, changing the `name` in the database and re-render that area again should be enough.

But be aware that updates of the osm database for that `osm_id` in the future might overwrite your custom name change. So a more robust solution'd be to change the SQL queries in the style to replace names based either on hardcoded `osm_id`s in the query or by creating your own additional database table, in which you store `osm_id` with `name`-replacement pairs, which you then access in the queries.

**Comment by maxim22m** [comment]
> 
> 
> If it's a name correction that applies to everywhere in the world (e.g. the name of a street changed), which should apply to every OSM instance in the world, then that change should be done on https://openstreetmap.org
> 
> And if you only want to replace the name in your own local OSM instance:
> 
> If I remember correctly the osm-carto [style](https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml) by default uses the names from dedicated `name` columns in the tables and not from the `name` tag inside of the `tags` JSON data. Assuming you have the right `osm_id`, changing the `name` in the database and re-render that area again should be enough.
> 
> But be aware that updates of the osm database for that `osm_id` in the future might overwrite your custom name change. So a more robust solution'd be to change the SQL queries in the style to replace names based either on hardcoded `osm_id`s in the query or by creating your own additional database table, in which you store `osm_id` with `name`-replacement pairs (primary key would be `osm_id`), which you then access in the queries.

would you exactly mention witch field in witch table must be edited, please?
I want to edit name of this [osm_id ](https://www.openstreetmap.org/relation/32246)locally and that's no matters later updates.
I edit name tag in planet_osm_rels table with 32246 record id then render again from zoom 0 to 10 (with render area and also global with remove persistent tiles and create it again), but nothing be changed.

**Comment by maxim22m** [comment]
I do it with update same negative osm_id (-32246) in planet_osm_polygon table. render it again and finished as well as desire.

**Comment by galewis2** [comment]
Not applicable to this repo.
