### ISSUE TITLE
Problems with parsing planet-latest.osm.pbf PBF  parser

### ISSUE THREAD

**Issue by dmwharris** [Overv/openstreetmap-tile-server#227]
Hey guys, 
I'm having a problem with loading planet-latest.osm.pbf into a docker container, using the steps provided on this site.  Twice now, I've gotten the same error, "Osm2pgsql failed due to ERROR: failed to uncompress data: data error".   The message snippet associated with reading in the planet .pbf file is " Reading in file: /data.osm.pbf
Using PBF parser.
Processing: Node(2624240k 375.3k/s) Way(0k 0.00k/s) Relation(0 0.00/s)node cache: stored: 98709546(3.76%), storage efficiency: 94.14% (dense blocks: 11648, sparse nodes: 4719551), hit rate: 0.00%
Osm2pgsql failed due to ERROR: failed to uncompress data: data error".       You can see that a lot of data is read in before this occurs.   I'm not sure why this continues to happen.

Here's the complete record:
renderaccount@ubuntu:/home/renderaccount/Downloads$ docker run -v /home/renderaccount/Downloads/planet-latest.osm.pbf:/data.osm.pbf -v openstreetmap-data:/var/lib/postgresql/12/main overv/openstreetmap-tile-server:1.3.10 import
Unable to find image 'overv/openstreetmap-tile-server:1.3.10' locally
1.3.10: Pulling from overv/openstreetmap-tile-server
5c939e3a4d10: Pull complete 
c63719cdbe7a: Pull complete 
19a861ea6baf: Pull complete 
651c9d2d6c4f: Pull complete 
20d5d553b676: Pull complete 
03e39318cf30: Pull complete 
b7fae1a354e1: Pull complete 
83da7b9f3fcf: Pull complete 
2536976753b6: Pull complete 
ba76951a7d00: Pull complete 
dfa4f999acdb: Pull complete 
6f7275614a93: Pull complete 
3c4441f2a065: Pull complete 
5eb03131adc0: Pull complete 
bed5e015bdcf: Pull complete 
6fd6c11b8517: Pull complete 
db2718086bb7: Pull complete 
efa52e8d03e5: Pull complete 
6cee10b4d6d0: Pull complete 
610890d6866d: Pull complete 
1919db048edc: Pull complete 
d35b0d6f94e1: Pull complete 
83e3818604f3: Pull complete 
60fb6ebeaa83: Pull complete 
4eacac0cce06: Pull complete 
Digest: sha256:9526b4e3c93534dd7adb06fba83f938b87f3c7e1634ecc2a32e676d8b8713910
Status: Downloaded newer image for overv/openstreetmap-tile-server:1.3.10
+ '[' 1 -ne 1 ']'
+ '[' import = import ']'
+ chown postgres:postgres -R /var/lib/postgresql
+ '[' '!' -f /var/lib/postgresql/12/main/PG_VERSION ']'
+ createPostgresConfig
+ cp /etc/postgresql/12/main/postgresql.custom.conf.tmpl /etc/postgresql/12/main/conf.d/postgresql.custom.conf
+ sudo -u postgres echo 'autovacuum = on'
+ cat /etc/postgresql/12/main/conf.d/postgresql.custom.conf
# Suggested minimal settings from
# https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/

shared_buffers = 128MB
min_wal_size = 1GB
max_wal_size = 2GB
maintenance_work_mem = 256MB

# Suggested settings from
# https://github.com/openstreetmap/chef/blob/master/roles/tile.rb#L38-L45

max_connections = 250
temp_buffers = 32MB
work_mem = 128MB
wal_buffers = 1024kB
wal_writer_delay = 500ms
commit_delay = 10000
# checkpoint_segments = 60 # unrecognized in psql 10.7.1
max_wal_size = 2880MB
random_page_cost = 1.1
track_activity_query_size = 16384
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_scale_factor = 0.02

listen_addresses = '*'
autovacuum = on
+ service postgresql start
 * Starting PostgreSQL 12 database server
   ...done.
+ sudo -u postgres createuser renderer
createuser: error: creation of new role failed: ERROR:  role "renderer" already exists
+ sudo -u postgres createdb -E UTF8 -O renderer gis
createdb: error: database creation failed: ERROR:  database "gis" already exists
+ sudo -u postgres psql -d gis -c 'CREATE EXTENSION postgis;'
ERROR:  extension "postgis" already exists
+ sudo -u postgres psql -d gis -c 'CREATE EXTENSION hstore;'
ERROR:  extension "hstore" already exists
+ sudo -u postgres psql -d gis -c 'ALTER TABLE geometry_columns OWNER TO renderer;'
ALTER TABLE
+ sudo -u postgres psql -d gis -c 'ALTER TABLE spatial_ref_sys OWNER TO renderer;'
ALTER TABLE
+ setPostgresPassword
+ sudo -u postgres psql -c 'ALTER USER renderer PASSWORD '\''renderer'\'''
ALTER ROLE
+ '[' '!' -f /data.osm.pbf ']'
+ '[' disabled = enabled ']'
+ '[' -f /data.poly ']'
+ sudo -u renderer osm2pgsql -d gis --create --slim -G --hstore --tag-transform-script /home/renderer/src/openstreetmap-carto/openstreetmap-carto.lua --number-processes 4 -S /home/renderer/src/openstreetmap-carto/openstreetmap-carto.style /data.osm.pbf
osm2pgsql version 1.2.0 (64 bit id space)

Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=800MB, maxblocks=12800*65536, allocation method=11
Mid: pgsql, cache=800
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Using lua based tag processing pipeline with script /home/renderer/src/openstreetmap-carto/openstreetmap-carto.lua
Using projection SRS 3857 (Spherical Mercator)
Setting up table: planet_osm_point
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads

Reading in file: /data.osm.pbf
Using PBF parser.
Processing: Node(2624240k 375.3k/s) Way(0k 0.00k/s) Relation(0 0.00/s)node cache: stored: 98709546(3.76%), storage efficiency: 94.14% (dense blocks: 11648, sparse nodes: 4719551), hit rate: 0.00%
Osm2pgsql failed due to ERROR: failed to uncompress data: data error
+ sudo -u postgres psql -d gis -f indexes.sql
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX

Any reasons I'm getting these uncompres errors?  I know the planet file is huge, but I need to use this one.  Thanks!

**Comment by Istador** [comment]
Any reason for using version `1.3.10` from two years ago instead of the latest `v1.8.1`?

**Comment by dmwharris** [comment]
No, I left that out later, but the docker actually automatically provides the latest.

**Comment by galewis2** [comment]
Sounds like a data corruption issue

**Comment by SomeoneElseOSM** [comment]
For info, 1.3.10 is likely coming from https://switch2osm.org/serving-tiles/using-a-docker-container/ .
I hardcoded that there because of problems with "bleeding edge" releases here not working.
