### ISSUE TITLE
Problem 404 some times

### ISSUE THREAD

**Issue by mvbelik** [Overv/openstreetmap-tile-server#229]
Good afternoon, I have such a problem, there are two servers absolutely identical, there is also an nginx load balancer and in which it balances requests to maps. The problem is that one server is working correctly, the second gives 404 errors periodically. If you take a line from the log file that he could not give, and paste it into the browser, then the picture opens. What should I pay attention to? There is nothing criminal in the logs.
The application is launched via docker-compose:
version: "3"
services:
start of tiles:
image: overv/openstreetmap-tile-server: v1.8.0
restart: always
size of shm_size: 64 g
health check:
test: ["CMD", "curl", "-f", "http://127.0.0.1:80 "]
interval: 5
seconds timeout: 10
seconds retries: 3
container name: tiles-server
Volumes:
- "{{tiles_db_dir}}:/var/lib/postgresql/12/main"
- "{{tiles_cache_dir}}/tiles:/var/lib/mod_tile"
- "{{settings_dir}}/indexes.sql:/indexes.sql"
ports:
- "8082:80"
- "5433:5432"
environment:
THREADS: "{{tiles_work_threads}}"
PASSWORD PGPASSWORD: "{{tiles_db_pass}}"
OSM2PGSQL_EXTRA_ARGS: "-C 32768"
command: "run"

**Comment by galewis2** [comment]
Is this still an issue?

**Comment by devinfra1** [comment]
Good morning,

I am currently having the same problem. Some tiles are returning 404.

How did you solve this problem?
