### ISSUE TITLE
plugins for leaflet

### ISSUE THREAD

**Issue by BlackWolfDEsign** [Overv/openstreetmap-tile-server#23]
Hi its possible to install plugins for leaflet? Thx for your great work

**Comment by Overv** [comment]
What kind of plugins do you mean?

**Comment by BlackWolfDEsign** [comment]
for example leaflet-search: https://github.com/stefanocudini/leaflet-search

I wanted to see if there was a suitable folder, but my new .osm.pbf extraction takes some time. ^^

**Comment by Overv** [comment]
Well, yes, there's nothing special about the Leaflet to view these maps. You can do anything with it that you would otherwise do with Leaflet.
