### ISSUE TITLE
Can I search by location name?

### ISSUE THREAD

**Issue by Bill-zy** [Overv/openstreetmap-tile-server#235]
I have an idea to fuzzy match according to the name or name:en in the postgresql database table.
I look forward to your solution.
thanks！

**Comment by Matt-PMCT** [comment]
Based on your brief description I think you might want to look at[ Nominatim](https://nominatim.org/).

But beware of this issue (https://github.com/Overv/openstreetmap-tile-server/issues/218) you won't be able to use this repository and Nominatim together.
