### ISSUE TITLE
Duplicate value in PostgreSQL custom config template

### ISSUE THREAD

**Issue by bitmstr** [Overv/openstreetmap-tile-server#237]
I noticed that "max_wal_size" has two entries in the PostgreSQL config file (`postgresql.custom.conf.tmpl`). I assume this was unintentional.

**Comment by Overv** [comment]
@gakowalski Which value would you say is right?

**Comment by gakowalski** [comment]
> I assume this was unintentional.
It was intentional as both config values come from different set of recommendations and I wanted end user to **know** the difference. In the end, only the last one is used.

> @gakowalski Which value would you say is right?
The second one.

**Comment by bitmstr** [comment]
Thank you @gakowalski for the clarification.
