### ISSUE TITLE
Permission Error on RHEL/CENTOS 8

### ISSUE THREAD

**Issue by BudDavis** [Overv/openstreetmap-tile-server#240]
Following the instructions on CentOS/RHEL 8, got an error that permissions were wrong.  The below patch made it go away:
 
--- a/run.sh
+++ b/run.sh
@@ -5,6 +5,7 @@ set -euo pipefail
 function createPostgresConfig() {
   cp /etc/postgresql/12/main/postgresql.custom.conf.tmpl /etc/postgresql/12/main/conf.d/postgresql.custom.conf
   sudo -u postgres echo "autovacuum = $AUTOVACUUM" >> /etc/postgresql/12/main/conf.d/postgresql.custom.conf
+  chmod -R 0750 /var/lib/postgresql/12/main
   cat /etc/postgresql/12/main/conf.d/postgresql.custom.conf
 }
 
for docker dummies like me, make the change to run.sh, do a make, and then follow the instructions.

--bud davis

**Comment by galewis2** [comment]
Do you want to open a PR?

**Comment by BudDavis** [comment]
no.  please ignore the above.  i was stupid about docker.  turn off selinux, it will make your life a lot easier !

**Comment by BudDavis** [comment]
OBE.
