### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by Overv** [Overv/openstreetmap-tile-server#242]
When I created this repository I was aiming to turn the [instructions for manually setting up a tile server](https://switch2osm.org/serving-tiles/manually-building-a-tile-server-18-04-lts/) into a Docker image to easily set up a tile server on my own VPS due to the obscene new pricing of Google Maps. My use case did not require frequent updates to the maps since the area I was interested in was already fully mapped and small changes to the geography didn't matter much for my use case, where the map served more as a background than a feature in and of itself. I posted the end result online so that other people could also easily set up the same thing.

Since then this repository has kind of blown up with a whole bunch of new features (automatic tile updates, performance tuning, software updates) and a lot of GitHub issues from people asking for support. The problem is that I haven't personally used this Docker image (any of its functionality) for multiple years now and I never used the tile updating functionality myself, which made it hard to review related pull requests and has resulted in several broken releases simply because I wasn't familiar enough with the implementation and wasn't able to effectively test it. I also currently only have a very small amount of time to work on my open source projects in general, so I'm no longer able to maintain this repository.

As far as I can tell, that leaves me with two options:

1. Stop maintaining this repository and mark it as read-only after which someone may fork the project and continue.
2. Or, assign someone else as the primary maintainer of this repository who is able to clean up the repository and maintain a certain level of quality.

So my question would be: is anyone interested in continuing this project and would they prefer to fork it, or continue the work in the original repository?

**Comment by galewis2** [comment]
I'm certainly interested in keeping this alive, but I'm not 100% sure how much effort I could provide on an ongoing basis to maintain this. I'm a big believer in not forking this for visibility and ensuring the community can maintain it itself.

I don't mind co-maintaining it!

**Comment by dbahrdt** [comment]
I'm currently maintaining a fork at https://github.com/fmi-alg/openstreetmap-tile-server. We're actively using almost all functionality including updates. We run our own tile server based on the planet data set with minute updates. We're currently in the process of transferring the project to another person since I'm leaving the university at the end of September. I hope that person can also co-maintain this project. I'll get back to you as soon as I have more information.

**Comment by galewis2** [comment]
@Overv Thinking about it now, I can definitely spend some ongoing time maintaining this project as you can see I'm contributing quite a bit for satisfying some other use-cases

**Comment by nielsole** [comment]
Hi Overv,
thanks for putting this repo up and maintaining it up to today!
I am pretty much in the same boat as galewis2, not sure how reliably and long-term I can put in time and keep my own interest up.
I [wrote a static tile server for mod_tile metatiles](https://github.com/nielsole/go_tile), but haven't had much other OSM experience.
I would hate to see this awesome repo go into read-only mode though. So if no one else steps up, I would be happy to keep the lights on or co-maintain.

**Comment by galewis2** [comment]
@nielsole I agree, and I figure the best bet is to get a couple co-maintainers that way there's less single points of failure, and we can share the responsibility

**Comment by Overv** [comment]
@dbahrdt I love the work you've been doing with regards to documenting the project. I would be very happy to merge your contributions so far.

I like the idea of having several co-maintainers who can work on this project whenever they have the time. How would you feel if I made all three of you co-maintainers? (@galewis2, @dbahrdt, @nielsole)

@Istador I would be happy to have you on board as well, especially with all of the work you've put into responding to issues. Only if you want to, of course.

**Comment by galewis2** [comment]
@Overv  Sounds awesome, I would actually prefer to be a co-maintainer as I think that would make this project healthier over the long term, especially with PR approvals requiring us to get approval and produce good improvements 😄

**Comment by Overv** [comment]
Great to hear :grin: I've gone ahead and sent collaborator invites to @galewis2, @dbahrdt and @nielsole.

**Comment by slachiewicz** [comment]
I can also help - currently, I have an open project where we will use this component.

**Comment by Overv** [comment]
@slachiewicz Thanks for offering. I think there are enough collaborators right now, but I'll keep it in mind if any new ones are needed in the future :)
