### ISSUE TITLE
Does not work on MacOS 12.1 

### ISSUE THREAD

**Issue by mikepaynedev** [Overv/openstreetmap-tile-server#245]
First of all thank you so much for what seems like such a huge amount of work and an extremely useful toolset. However I can't get this to work on MacOS. I've googled this error and it seems to suggest that the source data file does not exist, but you'll see in the screenshot that it in fact does. I've tried using --mount too.

I've tried several directories.

Any advice would be massively appreciated. 

Thanks

Mike
![Screenshot 2022-02-08 at 11 48 10](https://user-images.githubusercontent.com/60539094/152981647-9b79335e-8faf-476c-8f2f-cbc70cd21905.png)
![Screenshot 2022-02-08 at 11 47 11](https://user-images.githubusercontent.com/60539094/152981653-d90214c7-29f9-48cc-80b8-131510f1e09b.png)

**Comment by nielsole** [comment]
What is your docker setup? (docker desktop, installed via brew, etc.)
sounds like you have an issue with sharing folders in general.

```
echo "Hello World" > /tmp/docker-test.txt && docker run --rm -it -v /tmp/docker-test.txt:/test.txt ubuntu cat /test.txt
```

what does the above output?

**Comment by mikepaynedev** [comment]
@nielsole Thank you so much for the fast reply. You are right, as follows:
```
 /tmp % echo "Hello World" > /tmp/docker-test.txt && docker run --rm -it -v /tmp/docker-test.txt:/test.txt ubuntu cat /test.txt

cat: /test.txt: Is a directory
```
You can probably tell I am no docker expert. I originally had Docker Desktop installed but removed it then installed via brew. Any suggestions or pointers you can give me are greatly appreciated.

**Comment by nielsole** [comment]
the expected output in a working setup is `Hello World` so volume sharing in general does indeed not work in your setup. 
Probably this is due to you using docker-machine. And with your docker command you actually share the location within `/temp` **on the docker-machine VM** with the docker container.
This is unrelated to this repo, so I will not dive deeper. I guess it would work out of the box with Docker for Mac.

**Comment by mikepaynedev** [comment]
Thank you. Maybe worth leaving this around in case anyone else encounters it depending on your policy, but of course, close as not related to the repo. I'll investigate my docker setup further and spend some time on SO. Thanks again.

**Comment by nielsole** [comment]
if you run `docker-machine ssh` and then download the file from within that shell to your location in /tmp/data.osm.pbf it might just work ;)

**Comment by mikepaynedev** [comment]
Thank you very much, but sadly:
 foldername % docker-machine ssh
open /Users/username/.docker/machine/machines/default/config.json: permission denied
  foldername % sudo docker-machine ssh
Error: Cannot run SSH command: Host "default" is not running

**Comment by mikepaynedev** [comment]
For the benefit of others - I was able to resolve this by running
```
brew uninstall docker
brew uninstall docker-machine

```
then installing docker desktop.

Note to self - actually learn how these things work under the hood to avoid pain.

Massive thanks to @nielsole for your help and guidance.
