### ISSUE TITLE
Bug? Enhancement? /var/lib/mod_tile

### ISSUE THREAD

**Issue by johnjore** [Overv/openstreetmap-tile-server#246]
If I use UPDATES or a Poly file on a new docker container, I get build errors like this:
`cp: cannot create regular file '/var/lib/mod_tile/data.poly': Permission denied`

I have
```
        -v /mnt/osm/data:/var/lib/postgresql/12/main \
        -v /mnt/osm/rendered-tiles:/var/lib/mod_tile \
```
as part of my Dockerfile to preserve the rendered tiles as my computer is not the most powerful...

In the run.sh script
`chown postgres:postgres -R /var/lib/postgresql`
sets the permissions for the first one, but there is nothing for the 2nd volume.

Can/should `chown renderer:root -R /var/lib/mod_tile` be added to the script in the import section?
Happy to submit a PR if someone can confirm this is correct. Maybe something like this

```
if [ "$1" = "import" ]; then
          # Ensure the tile directory is in right state
          chown renderer:root -R /var/lib/mod_tile
```

Thoughts?

**Comment by galewis2** [comment]
I haven't noticed that problem, but I haven't used a POLY file. Feel free to open a PR with a script in the PR to ease duplication of the original issue :)
