### ISSUE TITLE
Allow higher zoom levels

### ISSUE THREAD

**Issue by TheWeirdDev** [Overv/openstreetmap-tile-server#247]
Is there any way to allow zoom levels higher than 20?

**Comment by eduardo-araujo-isi** [comment]
How did you set a zoom greater than 20? @TheWeirdDev

**Comment by TheWeirdDev** [comment]
> How did you set a zoom greater than 20? @TheWeirdDev

I forked the `mod_tile` project and modified it to allow higher zoom levels (up to 24)
You can find my fork [here](https://github.com/TheWeirdDev/mod_tile).

The older version of the tileserver had a link to the original repo and I replaced it with mine and it built and ran fine, but seems like it has changed since then. You have to figure out how to replace the original mod_tile with mine.

**Comment by TheWeirdDev** [comment]
It should be something like this: (I didn't test it and it might not work, you are on your own, Good Luck)

```Dockerfile
RUN cd ~ \
&& git clone --single-branch https://github.com/TheWeirdDev/mod_tile --depth 1 \
&& cd mod_tile \
&& ./autogen.sh \
&& ./configure \
&& make -j $(nproc) \
&& checkinstall --pkgversion="1" --install=no --pkgname "renderd" --default make install \
&& checkinstall --pkgversion="1" --install=no --pkgname "mod_tile" --default make install-mod_tile
```
