### ISSUE TITLE
Database size growing

### ISSUE THREAD

**Issue by david-nalta** [Overv/openstreetmap-tile-server#251]
Hi,

First of all, many thanks to Overv and all the contributors for this project.

I have set up this container on a server to provide tiles for one of our project.
I've managed to get it work but i'm having an issue with the database size.
My data folder which is mounted to host the postgresql database is 125 Go.
One week ago it was "only" 100 Go.
I find this suspicious, but as i lack experience on OpenStreetMap hosting maybe it's just normal.

2 pbf files from [https://download.openstreetmap.fr/extracts/europe/france/aquitaine/](https://download.openstreetmap.fr/extracts/europe/france/aquitaine/) were merged to provide datas for the import process.

The tiles have been rendered from zoom 12 to 18 using these coordinates [-0.78 43.07 0.09 43.57](http://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=-0.78,43.07,0.09,43.57)
According to the tile calculator from tools.geofabrik.de my tiles folder should be 1.5 Go and it's in fact 1.4 Go.
I've also enabled updates but i've never updated the pbf files.

What's bother me is that i couldn't find any way to calculate the approximate size of the database and i need to choose a size for this vitual hard disk.

Any help would be appreciated

**Comment by galewis2** [comment]
Do you have any indication of whether it is indexes, actual tables or otherwise? I haven't looked too closely at the size growth of my local DB, but I don't expect it to grow too rapidly

**Comment by david-nalta** [comment]
Thank you both for your answer and sorry for late responding.
I'll try to give answers asap to your 2 good questions

**Comment by david-nalta** [comment]
So, here is the sizes of my tables seen by dbeaver
![image](https://user-images.githubusercontent.com/101103440/160356936-4ac68985-b3cb-4f03-b4f9-cdb14a59da92.png)

So i think my database is getting simply too much unusefull data. As going through the datas, i can see some locations are clearly out of the limits defined by the pbf files.

I've also checked my /var/lib/mod_tile/ folder and there is no *.poly file in it.
![image](https://user-images.githubusercontent.com/101103440/160359145-c0f3ff09-5c65-4878-8b73-6e1d42382528.png)

And i'm pretty sure i didn't provide any *.poly while setting up this.
Checked my /var/log/tiles folder, but it's empty.

I've decide to disabled updates for now.

Thank you again for your time.

**Comment by Istador** [comment]
Hmm, I'm not sure, but I think that without a `poly` file the automatic update is applying the `planet.osm` updates unfiltered (because it doesn't have the region bounds from the `poly` file to trim everything outside of bound). The update will then create new entries out of bounds, if there are updates for them.

https://github.com/Overv/openstreetmap-tile-server/blob/f1203714c16be885b2aaa1a9d2790b40d4047a83/openstreetmap-tiles-update-expire#L149-L156

**Comment by david-nalta** [comment]
Ok, so i think my mistake is obvious now.
While i'm thanking you all once more, i have two last questions before closing this issue: 
- The TRIM_REGION_OPTIONS parameter seems to take both poly files and coordinates as value. Do the coordinates way works?
- If i provide a correct TRIM_REGION_OPTIONS value and enable again updates, will my database self clean? (I don't really believe in this but would be so cool 😅)

**Comment by Istador** [comment]
> * The TRIM_REGION_OPTIONS parameter seems to take both poly files and coordinates as value. Do the coordinates way works?

Likely, providing a bounding box should work just as fine as a poly file.

https://github.com/Overv/openstreetmap-tile-server/blob/f1203714c16be885b2aaa1a9d2790b40d4047a83/openstreetmap-tiles-update-expire#L33-L34

See [trim_osc.py](https://github.com/Zverik/regional/blob/a618ea42ea802f13ba7cd4ba218ed8d82e4cf95f/trim_osc.py#L83-L88)

---

> * If i provide a correct TRIM_REGION_OPTIONS value and enable again updates, will my database self clean? (I don't really believe in this but would be so cool sweat_smile)

I don't think so. If I understand [trim_osc.py](https://github.com/Zverik/regional/blob/a618ea42ea802f13ba7cd4ba218ed8d82e4cf95f/trim_osc.py#L116-L131) correctly, then objects that are out of bounds but are already in the database are treated like objects that are in-bounds.

(It puts them temporarily inside `nodesM`/`waysM` and then checks if they are in the database, and adds them to `nodes`/`ways` if they are.)

**Comment by david-nalta** [comment]
All is clear 😊
Thank you everyone for helping me solve this.
