### ISSUE TITLE
Localhost?

### ISSUE THREAD

**Issue by mickael-bdias** [Overv/openstreetmap-tile-server#252]
Hello everyone,

Quick questions:

 1.) Can I change port 80 to another one (Dockerfile)?
 Or I cannot, because of the Apache.

2.) Can I use this outside the local host?
 I am building a react-naive app and I needed another solution rather than Google Maps.
One comment on [React Native Maps](https://github.com/react-native-maps/react-native-maps/issues/3941) speaks about it but I am not sure.

Best regards,
 Mickaël Brás Dias

**Comment by Istador** [comment]
1.)

The ports declared as `EXPOSE` in a `Dockerfile` [aren't automatically exposed](https://forums.docker.com/t/what-is-the-use-of-expose-in-docker-file/37726/2). It can be best understand as something to document to other people which ports the image has to offer. You have to expose them manually with the `-p` argument (or publish them all to random ports via `-P`).

See https://github.com/Overv/openstreetmap-tile-server#running-the-server

https://github.com/Overv/openstreetmap-tile-server/blob/672e2cd5b3b45ea36d9777867de4618b4c0ebe68/README.md#L54-L67

---

2.)

What you do with it is up to you. It's open source, so you can use it for whatever you want.

Inside the docker image runs a HTTP server whose port can be exposed to the outside network. If you install and run it on a productive server on the internet, then other users can send HTTP requests to it and get the image tiles as a response.

**Comment by mickael-bdias** [comment]
Hi @Istador!
Thanks for your insights. It was helpful.
