### ISSUE TITLE
Processing too slow

### ISSUE THREAD

**Issue by ladom-web** [Overv/openstreetmap-tile-server#255]
![slow](https://user-images.githubusercontent.com/77220913/161214479-a5f3e2c4-3f90-4c86-a63a-9a135a37db08.jpg)
I'm using win 10 and import the entire planet. Can it be faster?

**Comment by nielsole** [comment]
the entire planet is quite large so is expected to take a long while.
Also importing the entire planet is a one-off thing if you use replication.

**Comment by ladom-web** [comment]
It's already tacked 5 days.... too slow.... how long will it take?

**Comment by ladom-web** [comment]
I use this command:
docker run -v d://MapServer/planet-latest.osm.pbf:/data.osm.pbf -v openstreetmap-nodes:/nodes -v openstreetmap-data:/var/lib/postgresql/12/main -e "OSM2PGSQL_EXTRA_ARGS=--flat-nodes /nodes/flat_nodes.bin" overv/openstreetmap-tile-server import

**Comment by nielsole** [comment]
As Istador explained we are likely not planning any changes as we don't really optimize for performance, but for ease of use. Please feel free to post your findings in this threads anyways for others to find :)

**Comment by ladom-web** [comment]
what values of Way and Relation ​​to expect for world map?
