### ISSUE TITLE
http://193.151.129.56:9090//{1}/{2}/{3}.png

### ISSUE THREAD

**Issue by MohMehrnia** [Overv/openstreetmap-tile-server#258]
Address is not work an i can not use in app
http://193.151.129.56:9090//{1}/{2}/{3}.png

**Comment by Istador** [comment]
Likely you mean `http://193.151.129.56:9090/tile/{z}/{x}/{y}.png`:
https://github.com/Overv/openstreetmap-tile-server/blob/0f229a0cbdd6bf00ffde1b029da57560e20aee00/leaflet-demo.html#L28

But the server isn't responding on http://193.151.129.56:9090/tile/0/0/0.png, http://193.151.129.56:9090/0/0/0.png, http://193.151.129.56:8080/tile/0/0/0.png, nor http://193.151.129.56:8080/tile/0/0/0.png.

There is a webserver running on port 80 though http://193.151.129.56/ (503 Service Temporarily Unavailable).

What command are you using to `run` the docker container?
