### ISSUE TITLE
Challenges and questions from @stevo01

### ISSUE THREAD

**Issue by gakowalski** [Overv/openstreetmap-tile-server#26]
> Biggest challenges that I observed:
> - Import of the whole continent ( or planet ) needs long time. Not clear how to "tune" import process for particular machine.
> - Find a strategy to keep database up to date after initial import.
> - Find a way how to reproduce the setup of tile server on different machine (docker should be the solution here right?)
> - Diagnostics: How to recognise that something is not working, indicate problems to server owner and how to find the reason.
> 
> My questions:
> - do you plan to setup and maintain own tile server or do you know someone who runs a tile server for a long period of time?
> - can we share results of our investigations and try to find "best practice" method.

**Comment by gakowalski** [comment]
My answers:

> Biggest challenges that I observed:
> 1. Import of the whole continent ( or planet ) needs long time. Not clear how to "tune" import process for particular machine.

I've found out that turning off autovacuum in PostgreSQL speeds up import process by ~13% and switching to PostgreSQL 11 instead od 10 speeds up by another ~3%. Turning off autovacuum is quite simple, see this commit: https://github.com/pot-gov-pl/openstreetmap-tile-server/commit/662ce85cb8b84ccb8f63a9160c366c864968817d (removing 4 lines of `sudo` in this commit was an error reverted in the next commit: https://github.com/pot-gov-pl/openstreetmap-tile-server/commit/42b5783486ed1de2607f80955e768c511fcdaaf7).

Switching to PostgreSQL 11 is here: https://github.com/pot-gov-pl/openstreetmap-tile-server/commit/110a540c99e32ad3efa630a37e1d113af6edc5d0 (alas, it does not include edits in Makefile).

There may be other ways, but I did not focus on finding them.

> 2. Find a strategy to keep database up to date after initial import.

I haven't figured it out yet. This is a topic that I will have to deal with, because I have to update the server in the organization for which I work.

> 3. Find a way how to reproduce the setup of tile server on different machine (docker should be the solution here right?)

Docker is the solution.

> 4. Diagnostics: How to recognise that something is not working, indicate problems to server owner and how to find the reason.

You can monitor the consumption of resources by the container and check the logs. I use Portainer for container management and I can easily do some monitoring and log reading there. I think there are probably other container management applications that can manage it even better.

Actually, the reason for some of my changes in the container prepared by @Overv , was just that while monitoring the server I saw that something works very badly when network traffic increases for a short time (eg. 2000 users in the same time for 5 minutes). 8+ threads got allocated and there was a constant 100% load on all cores even after traffic decreased. 

> My questions:
> 5. do you plan to setup and maintain own tile server or do you know someone who runs a tile server for a long period of time?

I have been maintaining the tile server for at least half a year. However, I was interested only in the area of my country, I did not undertake to serve a larger area.

> 6. can we share results of our investigations and try to find "best practice" method.

Of course! Let's use the GitHub public space for this, so that others can use it and join our efforts.

**Comment by stevo01** [comment]
Thanks for feedback! I added some [benchmark test results](https://github.com/stevo01/openstreetmap-tile-server/blob/dev-stevo/Doc/Benchmarks.md) from osm imports on my machine und added [instructions ](https://github.com/stevo01/openstreetmap-tile-server/blob/dev-stevo/Doc/UsefulCommands.md) for the usage of the container.

**Comment by stevo01** [comment]
just for information: [logfile import europa latest](https://github.com/stevo01/openstreetmap-tile-server/blob/dev-stevo/Doc/Benchmarks/osm-import/import_europa-latest_002.log)

- Machine: AMD Ryzon 8 Core, 64GByte RAM, 1TB NVMe
- docker image size after import: around 500G
- overall time 17.2 hours
- used docker container [3fc7120](https://github.com/stevo01/openstreetmap-tile-server/commit/3fc7120432a2c70672e77e13b1cfa4718e45fcee)
