### ISSUE TITLE
How generate tiles from other source ?

### ISSUE THREAD

**Issue by KevinBTech** [Overv/openstreetmap-tile-server#267]
I would like to import layer from other source that OSM or GeoFabriks (KML files ou GeoJson files).
If I undestood correctly, I have to previously convert GeoJsonFile (or KML) to pbf.
I could use leaflet plugin to use geojson layer, but files could be heavy (100MB to 2GB).

Finaly, I would be able to use the import command with those new pbf files.

Should I create a OSM server by layer or once for all ?
What do you think about it ? Is this a bad idea ? 
(I consider that some users here have more experiences and had already did the same thing)

PS : I would like to provid an OSM instance , with base layer and multiples layers, without an access to internet.

**Comment by galewis2** [comment]
Hi @KevinBTech , importing files other than OSM PBFs are definitely outside the scope of this project. If you really want to, you'd have to convert to PBF (I have no experience with https://github.com/roelderickx/ogr2osm ) and then re-style, etc. But it would be a major undertaking
