### ISSUE TITLE
World map Value

### ISSUE THREAD

**Issue by ladom-web** [Overv/openstreetmap-tile-server#270]
![value](https://user-images.githubusercontent.com/77220913/164592162-d1a8246c-9d16-4582-ac2b-69253178ddf1.png)
what values of Way and Relation ​​to expect for world map?

**Comment by nielsole** [comment]
I've never done a world import, but this should give an indication: https://wiki.openstreetmap.org/wiki/File:Osmdbstats2.png
~800.000.000 ways, ~10.000.000 relations

**Comment by RadekHavelka** [comment]
last year I did full planet import with following numbers

2021-02-07 22:53:59    Processed 6634698177 nodes in 5524s (1h 32m 4s) - 1201k/s
2021-02-07 22:53:59    Processed 733743019 ways in 303789s (84h 23m 9s) - 2k/s
2021-02-07 22:53:59    Processed 8593984 relations in 400769s (111h 19m 29s) - 21/s

**Comment by Istador** [comment]
The most recent values for the full osm planet can be found here:
- https://planet.openstreetmap.org/statistics/data_stats.html

```
Number of nodes     | 7646463672
Number of ways      | 854479032
Number of relations | 9855838
````
(as of `2022-04-24 22:00:04 UTC`)
