### ISSUE TITLE
Merge multiple polygon files

### ISSUE THREAD

**Issue by thewire247** [Overv/openstreetmap-tile-server#272]
Issue #268 has been very useful thanks, I managed to get the files merged. Following on from that, how would I merge the polygon files?

**Comment by Istador** [comment]
See this for the format definition with an example of two areas in one file:
https://wiki.openstreetmap.org/wiki/Osmosis/Polygon_Filter_File_Format

It does say:
> Several of these files may be combined to one multi-sectioned file. In this case each section must be separated from its preceding section by an empty line (combined files are used by the programs [osmrelpoly](https://wiki.openstreetmap.org/wiki/Osmrelpoly) and [osmassignpoly](https://wiki.openstreetmap.org/wiki/Osmassignpoly)).

and based on that this should be enough to do the job:
```bash
# merge first.poly and second.poly
( cat first.poly && echo "" && cat second.poly ) >merged.poly

# merge first.poly, second.poly and third.poly
( cat first.poly && echo "" && cat second.poly && echo "" && cat third.poly ) >merged.poly
```

---

If that doesn't work (e.g. if `osmosis` doesn't support it, which I don't know), I'd suggest combining the contents into one section:
```bash
# merge first.poly and second.poly
( head -n -1 first.poly && echo 2 && tail -n +3 second.poly ) >merged.poly

# merge first.poly, second.poly and third.poly
( head -n -1 first.poly && echo 2 && ( tail -n +3 second.poly | head -n -1 ) && echo 3 && tail -n +3 third.poly ) >merged.poly
```
