### ISSUE TITLE
/data/region.osm.pbf Permission Denied

### ISSUE THREAD

**Issue by ZDawe** [Overv/openstreetmap-tile-server#277]
Hello,

When attempting to import an osm.pbf file I have called /home/user/planet.osm.pbf with this line 

`sudo docker run -v /home/user/Documents/planet-220502.osm.pbf:/data/region.osm.pbf -v osm-data:/data/database/ overv/openstreetmap-tile-server import`
![error](https://user-images.githubusercontent.com/63648579/168614890-4d966182-8026-4822-a977-3b2961695502.png)

And after it begins to access the PostGIS and begins setting up tables for planet_osm, it gives me this error

`ERROR: Open failed for '/data/region.osm.pbf'`

I have attempted to give myself elevated privileges to get around this issue, but I have so far been unsuccessful. Does anyone know how to get the appropriate permissions to do such?

**Comment by Istador** [comment]
What are the file permissions of `/home/user/Documents/planet-220502.osm.pbf`?
```
ls -lan /home/user/Documents/planet-220502.osm.pbf
```

The `osm2pgsql` command is executed as user `renderer` (uid/gid: 1000), which needs to be able to access the file. (Regardeless of your `sudo`, the `run.sh` is executed as `root` anyway, but inside of it the script assumes other roles for some sub commands.)

If in question execute one or both of:
```
chmod 777 /home/user/Documents/planet-220502.osm.pbf
chown 1000:1000 /home/user/Documents/planet-220502.osm.pbf
```
