### ISSUE TITLE
Beginners Problem: Just can't get it to work

### ISSUE THREAD

**Issue by gsontheimer** [Overv/openstreetmap-tile-server#280]
I have installed Docker on my Intel / Win10 Laptop, went though the Getting Started training - everything worked as advertised.

I started the two Commands below as described here, but Port 8080 only gives an empty page with a Plus/minus sign in the top left corner, no Tiles. And QGIS only gets timeout errors - what am I doing wrong?

docker run \
    -v /docker/south-africa-and-lesotho-latest.osm.pbf:/data/region.osm.pbf \
    -v osm-data:/data/database/ \
    -v osm-tiles:/data/tiles/ \
    overv/openstreetmap-tile-server \
    import

docker run \
    -p 8080:80 \
    -v osm-data:/data/database/ \
    -v osm-tiles:/data/tiles/ \
    -d overv/openstreetmap-tile-server \
    run

**Comment by Istador** [comment]
Please check your `import` and `run` logs. Likely there was some problem during `import` and the database is empty.

```
docker container ls --all | grep overv
docker logs ${container_id}
```

Consider using `//` instead of `/` on windows for the beginning of all absolute volume paths - even for those on the right side of the `:`. Sometimes that helps on Windows.

**Comment by gsontheimer** [comment]
Thank you very much! This pointed me in the right direction! I also suspected, that the problem was with the import.

This is what I founf in the documentation of Docker:

"On Windows, the paths must be specified using Windows-style semantics.".

So this is what I tried with success (in Windows PowerShell):

docker run `
    -v c:\docker\south-africa-and-lesotho-latest.osm.pbf:/data/region.osm.pbf `
    -v osm-data:/data/database/ `
    -v osm-tiles:/data/tiles/ `
    overv/openstreetmap-tile-server `
    import

==> The web browser shows with localhost:8080 a OSM up to the highest zoom level.

I tried to access the tile server with QGIS with the following connection: 
http://localhost:8080/tile/{z}/{x}/{y}.png

Next problem: It works up to zoom level 10. With zoom level 11 I get the following error:

Loading resulting layers
Algorithm 'Generate XYZ tiles (MBTiles)' finished
QGIS version: 3.22.5-Białowieża
QGIS code revision: c2723178
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.1
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 8.2.1, January 1st, 2022
PDAL version: 2.3.0 (git-version: 9f35b7)
Algorithm started at: 2022-05-18T17:50:45
Algorithm 'Generate XYZ tiles (MBTiles)' starting…
Input parameters:
{ 'BACKGROUND_COLOR' : QColor(0, 0, 0, 0), 'DPI' : 96, 'EXTENT' : '11.000000000,30.000000000,-30.000000000,-16.000000000 [EPSG:3857]', 'METATILESIZE' : 4, 'OUTPUT_FILE' : 'D:/OSM-TS 6-11.mbtiles', 'QUALITY' : 75, 'TILE_FORMAT' : 0, 'ZOOM_MAX' : 11, 'ZOOM_MIN' : 6 }

Using 16 CPU Threads:
Generating tiles for zoom level: 6
Generating tiles for zoom level: 7
Generating tiles for zoom level: 8
Generating tiles for zoom level: 9
Generating tiles for zoom level: 10
Traceback (most recent call last):
File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 455, in processAlgorithm
self.generate(writer, parameters, context, feedback)
File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 316, in generate
for result in threadPool.map(self.renderSingleMetatile, metatiles_by_zoom[zoom]):
File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\concurrent\futures\_base.py", line 608, in result_iterator
yield fs.pop().result()
File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\concurrent\futures\_base.py", line 438, in result
return self.__get_result()
File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
raise self._exception
File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\concurrent\futures\thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 230, in renderSingleMetatile
self.writer.write_tile(tile, tileImage)
File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 401, in write_tile
self._init_zoom_layer(tile.z)
File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 393, in _init_zoom_layer
self._execute_sqlite("UPDATE metadata SET value='{}' WHERE name='bounds'".format(bounds))
File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 373, in _execute_sqlite
conn.execute(cmd)
sqlite3.OperationalError: database is locked

Execution failed after 9.88 seconds

Anything I can change on the server side to get maps exported up to at least zoom level 13???

**Comment by gsontheimer** [comment]
Thank you for the hint! With only one thread QGIS works as expected. It seems that the rendering of tiles concurrently in different threds, presumably for different zoom levels, creates problems with locks in the database.
