### ISSUE TITLE
How to add osm-bright style?

### ISSUE THREAD

**Issue by Ler-Tor** [Overv/openstreetmap-tile-server#283]
I'm trying to add osm-bright style (https://github.com/mapbox/osm-bright). 
It has mml file, but doesn't have any lua script, .style file or SQL file.
How can I update style then?

**Comment by Istador** [comment]
The `osm2pgsql` command [recommended](https://github.com/mapbox/osm-bright/blob/f1c8780cd7fe9d707fca693a82fdca38b7a98936/README.md#using-osm2pgsql) by `osm-bright` comes without tag-transform-script and style parameters, so they aren't needed for this style.

Though in the `run.sh` of this project it is hardcoded.
https://github.com/Overv/openstreetmap-tile-server/blob/dc47871a5d32e6fa2ac6dc410a19feb3d3ce229c/run.sh#L99-L104

I don't know how to do this correctly.

Maybe you can provide an empty file that you reference using the `NAME_LUA` and `NAME_STYLE` environment variables?
Or maybe you can provide the parameters via `OSM2PGSQL_EXTRA_ARGS` a second time to unset them somehow? (By using `/dev/null` or an empty string?)
