### ISSUE TITLE
Environment variable for tile expiration min and max zoom

### ISSUE THREAD

**Issue by balchen** [Overv/openstreetmap-tile-server#295]
I have set up the tile server to run locally and it's working great with (almost) live updates as I update OSM. The only issue is that big tiles (low zoom levels) are not expired. Ideally, I would like to expire tiles to a lower zoom level than what is currently hard-coded in https://github.com/Overv/openstreetmap-tile-server/blob/010f87d71171638f81f18d892f0774643ae3bdeb/openstreetmap-tiles-update-expire#L60.

If these values could be environment variables instead, I could configure the zoom level for tile expiration to suit different needs. I'll happily submit a PR for a change.

**Comment by nielsole** [comment]
probably docs should be updated, too.
