### ISSUE TITLE
Setup on Azure: executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by trytocatchme** [Overv/openstreetmap-tile-server#298]
I'm trying to setup openstreetmap-tile-server on azure so I created docker volume and I would like to setup base version without importing .osm.pbf file(It works on my local computer but on azure not).

**Command**:
`docker run -v exxthstorageprod/osm-data:/data/database/ overv/openstreetmap-tile-server import`

**Error**
> Error: Failed to start container wonderful-lewin, Error response: to create containerd task: failed to create container d017a916fceff54c488b6cceb928dddaad240f48d3a63e38be6bf5c446643514: guest RPC failure: failed to create container: failed to run runc create/exec call for container d017a916fceff54c488b6cceb928dddaad240f48d3a63e38be6bf5c446643514 with exit status 1: container_linux.go:380: starting container process caused: exec: "import": executable file not found in $PATH: unknown

**Repro steps:**
1. Create storage account on Azure 
![image](https://user-images.githubusercontent.com/12458009/180400788-6cf69094-2cb4-49f3-b7ba-f4f136d11c90.png)
2. Create docker volume 
`docker volume create --storage-account exxthstorageprod osm-data`
![image](https://user-images.githubusercontent.com/12458009/180401360-a3c3a26d-8c7e-4a97-b80f-ffc0a5ef4596.png)
3. Run
`docker run -v exxthstorageprod/osm-data:/data/database/ overv/openstreetmap-tile-server import`

    Result:
     ![image](https://user-images.githubusercontent.com/12458009/180403379-7baaa441-4c63-471b-acd1-caf6f6bd5189.png)
     ![image](https://user-images.githubusercontent.com/12458009/180403138-f0905991-813b-4d4f-a487-2c1376a05dc7.png)

Any idea how to solve this problem or do you have any instruction how to setup it on azure?

**Comment by nielsole** [comment]
looks like whatever runtime you use doesn't respect `ENTRYPOINT`. try `docker run -v exxthstorageprod/osm-data:/data/database/ overv/openstreetmap-tile-server /run.sh import`

**Comment by trytocatchme** [comment]
I tried but it didn't help but I see one difference now. There are no events now.

![image](https://user-images.githubusercontent.com/12458009/180434459-7d746728-b6c9-4d7f-b479-bea10319f1b7.png)
![image](https://user-images.githubusercontent.com/12458009/180434589-25e6c870-70d2-44fe-8cac-caf960beeefc.png)

**Comment by nielsole** [comment]
Thanks for getting back with the results. Unfortunate we can't provide support for generic docker/proprietary vendor related issues. Let me know if this issue turns out to be related to this project and I will reopen.
