### ISSUE TITLE
Invalid volume specification

### ISSUE THREAD

**Issue by mpaine-act** [Overv/openstreetmap-tile-server#30]
Hello,

I am trying to execute the docker command line in PowerShell in Windows Server 2019 (using Hyper-V and PowerShell package Docker as DockerProvider), but I cannot get the openstreetmap-data volume to mount.   Here is the output when I try:

`PS D:\> docker volume ls
DRIVER              VOLUME NAME
local               openstreetmap-data

PS D:\> docker run -v openstreetmap-data:/var/lib/postgresql/10/main overv/openstreetmap-tile-server
C:\Program Files\Docker\docker.exe: Error response from daemon: invalid bind mount spec "openstreetmap-data:/var/lib/postgresql/10/main": invalid volume specification: 'openstreetmap-data:\var\lib\postgresql\10\main'.
See 'C:\Program Files\Docker\docker.exe run --help'.
`

**Comment by Istador** [comment]
I'm no docker on windows expert, but my windows colleagues often have problems with volumes (and windows line endings and missing execute bits for shell scripts).

Please try out the double slash syntax:
```
docker run -v openstreetmap-data://var/lib/postgresql/10/main overv/openstreetmap-tile-server run
```

**Comment by mpaine-act** [comment]
That was it, thank you very much.
