### ISSUE TITLE
Show download progress for polygon data

### ISSUE THREAD

**Issue by Unaimend** [Overv/openstreetmap-tile-server#301]
Hello OpenStreetMap team
It would be quite nice to see the download progress for, for example, the water polygon data. Because, for me, it now has been taking more than 30 minutes of downloading and it's still not finished

Sincerly,
Thomas

**Comment by Istador** [comment]
This issue should rather be opened in the [osm-carto](https://github.com/gravitystorm/openstreetmap-carto) repo, from where the [get-external-data.py](https://github.com/gravitystorm/openstreetmap-carto/blob/master/scripts/get-external-data.py) script is coming from.
