### ISSUE TITLE
Problem with ssl certificate 

### ISSUE THREAD

**Issue by danylonikolenko** [Overv/openstreetmap-tile-server#305]
Hello, I have run docker container with map on remote server Ubuntu and now it looks good. 
I have ssl certificates and want to open my map with https.

My apache.conf inside project folder 

```
`<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName some.site.com
    ServerAlias some.site.com

    LoadTileConfigFile /usr/local/etc/renderd.conf
    ModTileRenderdSocketName /var/run/renderd/renderd.sock
    ModTileRequestTimeout 0
    ModTileMissingRequestTimeout 30

    DocumentRoot /var/www/html

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    <IfDefine ALLOW_CORS>
        Header set Access-Control-Allow-Origin "*"
    </IfDefine>
</VirtualHost>

<VirtualHost *:443>
 ServerAdmin webmaster@localhost
    ServerName some.site.com
    ServerAlias some.site.com

    SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
    ProxyPreserveHost On
    SSLCertificateFile /root/open_street_map/ssl/some.site.fullchain.pem
    SSLCertificateKeyFile /root/open_street_map/ssl/jsome.site.key.pem

    LoadTileConfigFile /usr/local/etc/renderd.conf
    ModTileRenderdSocketName /var/run/renderd/renderd.sock
    ModTileRequestTimeout 0
    ModTileMissingRequestTimeout 30

    DocumentRoot /var/www/html

      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined

    <IfDefine ALLOW_CORS>
        Header set Access-Control-Allow-Origin "*"
    </IfDefine>


</VirtualHost>
`
```

But It does not work. Could somebody show me the right apache config?
Thank you !

**Comment by Istador** [comment]
> But It does not work.

What doesn't work?
Do you have an error message?
What does the log say?

---

How did you modify the `apache.conf`?
1. Did you modify the file inside the container directly?
2. Did you mount it as a volume?
3. Did you build your own container with an additional layer, copying in your modified version?
4. Did you clone this repository, modified the file and build your own image that you're using?

Have you mounted (volume) or copied into the container the key files, or are they only on your host system?`

I'd suggest mounting them to `/data/ssl/` and then using those paths inside the config (`/data/ssl/some.site.fullchain.pem` and `/data/ssl/jsome.site.key.pem`).
```
docker  run  [...]  \
  -v /root/open_street_map/ssl/:/data/ssl/  \
  overv/openstreetmap-tile-server
```

Or even better: don't put the keys into the osm container at all. But run a separate proxy container (e.g. traefik, nginx or apache) whose job is it just to deal with TLS on port 443 and tunnel the requests to the osm container. See issue #19.

**Comment by danylonikolenko** [comment]
@Istador Thank you so much! The problem was that the server settings did not get inside the container, I just went into the container and copied the settings from the project root (apache.conf).
