### ISSUE TITLE
Mapnik LOG> 2022-07-30 21:40:01: warning: unable to find face-name

### ISSUE THREAD

**Issue by zarevskaya** [Overv/openstreetmap-tile-server#306]
Hi,

I have an issue when i launch my docker. I can see the map, it's not a problem but i have this error:

![Capture d’écran du 2022-07-30 23-40-44](https://user-images.githubusercontent.com/60230221/181997026-dcae31cc-cb78-4387-947a-0fc16c916618.png)

Is it a big problem?

Thank you in advance :)

**Comment by Istador** [comment]
Some warnings are normal, because some of the fonts have slightly different names on different systems, so their names are listed redundantly.

But since the last updates there are a few more warnings than before. See issure #303

**Comment by zarevskaya** [comment]
Thank you very much!

**Comment by galewis2** [comment]
This will be resolved by https://github.com/Overv/openstreetmap-tile-server/pull/307
