### ISSUE TITLE
import europe - error

### ISSUE THREAD

**Issue by BlackWolfDEsign** [Overv/openstreetmap-tile-server#31]
Hi, do you have any idea, why?: (i want to import europe-latest.osm.pbf)

Reading in file: /data.osm.pbf
Using PBF parser.
Processing: Node(1720270k 335.7k/s) Way(0k 0.00k/s) Relation(0 0.00/s)/run.sh: line 44:   101 Killed                  sudo -u renderer osm2pgsql -d gis --create --slim -G --hstore --tag-transform-script /home/renderer/src/openstreetmap-carto/openstreetmap-carto.lua -C 2048 --number-processes ${THREADS:-4} -S /home/renderer/src/openstreetmap-carto/openstreetmap-carto.style /data.osm.pbf
+ service postgresql stop
 * Stopping PostgreSQL 10 database server
   ...done.
+ exit 0

**Comment by Overv** [comment]
It seems like the process was killed because it ran out of memory. How much memory does your machine have?

**Comment by BlackWolfDEsign** [comment]
32gb ;/

**Comment by Overv** [comment]
Hmm, could you run it again and see if it tries to use all of your RAM?

**Comment by BlackWolfDEsign** [comment]
same line, 102 Killed ^^. I use a smaller map for the time being

**Comment by BlackWolfDEsign** [comment]
hi it's me again. I tried again today the europe map. I increased also the memory but ...

`Processing: Node(1173720k 369.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)/run.sh: line 63:   151 Killed                  sudo -u renderer osm2pgsql -d gis --create --slim -G --hstore --tag-transform-script /home/renderer/src/openstreetmap-carto/openstreetmap-carto.lua -C 32079 --number-processes ${THREADS:-4} -S /home/renderer/src/openstreetmap-carto/openstreetmap-carto.style /data.osm.pbf
+ sudo -u postgres psql -d gis -f indexes.sql
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
+ service postgresql stop
 * Stopping PostgreSQL 10 database server
   ...done.
+ exit 0
`

**Comment by BlackWolfDEsign** [comment]
I tried again... now...

```
Processing: Node(1189780k 313.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)/run.sh: line 63:   152 Killed                  sudo -u renderer osm2pgsql -d gis --create --slim -G --hstore --tag-transform-script /home/renderer/src/openstreetmap-carto/openstreetmap-carto.lua -C 32079 --number-processes ${THREADS:-4} -S /home/renderer/src/openstreetmap-carto/openstreetmap-carto.style /data.osm.pbf
+ sudo -u postgres psql -d gis -f indexes.sql
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
+ service postgresql stop
 * Stopping PostgreSQL 10 database server
   ...done.
+ exit 0
```

**Comment by Pr0gmaT1k** [comment]
same here with https://planet.openstreetmap.org/
 i7-4770K, 16 GB, 500GB

**Comment by Pr0gmaT1k** [comment]
Well... 
Could it be fix ?
![image](https://user-images.githubusercontent.com/11977968/60548958-ba81dd80-9d23-11e9-8f63-2f80bda4c901.png)

**Comment by Istador** [comment]
Try to use `--oom-kill-disable` together with the `--memory="<number>g"` option for your `docker run` command.

[Docker run reference - User memory constraints](https://docs.docker.com/engine/reference/run/#user-memory-constraints):
> By default, kernel kills processes in a container if an out-of-memory (OOM) error occurs. To change this behaviour, use the `--oom-kill-disable` option. Only disable the OOM killer on containers where you have also set the `-m/--memory` option. If the `-m`` flag is not set, this can result in the host running out of memory and require killing the host’s system processes to free memory.

**Comment by Pr0gmaT1k** [comment]
`DB writer thread failed due to ERROR: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.`

**Comment by BlackWolfDEsign** [comment]
> Try to use `--oom-kill-disable` together with the `--memory="<number>g"` option for your `docker run` command.
> 
> [Docker run reference - User memory constraints](https://docs.docker.com/engine/reference/run/#user-memory-constraints):
> 
> > By default, kernel kills processes in a container if an out-of-memory (OOM) error occurs. To change this behaviour, use the `--oom-kill-disable` option. Only disable the OOM killer on containers where you have also set the `-m/--memory` option. If the `-m` flag is not set, this can result in the host running out of memory and require killing the host’s system processes to free memory.

does not helps me :( the same mistake as last

**Comment by BlackWolfDEsign** [comment]
only for the archive: i tried to import germany.osm.pbf
crashes alltime by creating indizes?

```
Setting up table: planet_osm_line
Setting up table: planet_osm_polygon
Setting up table: planet_osm_roads

Reading in file: /data.osm.pbf
Using PBF parser.
Processing: Node(303408k 153.2k/s) Way(49186k 25.07k/s) Relation(607290 75.13/s)  parse time: 12026s
Node stats: total(303408415), max(6587424866) in 1981s
Way stats: total(49186450), max(701418297) in 1962s
Relation stats: total(607291), max(9749498) in 8083s
Sorting data and creating indexes for planet_osm_roads
Sorting data and creating indexes for planet_osm_polygon
Sorting data and creating indexes for planet_osm_point
Sorting data and creating indexes for planet_osm_line
Copying planet_osm_roads to cluster by geometry finished
Creating geometry index on planet_osm_roads
Creating osm_id index on planet_osm_roads
Copying planet_osm_point to cluster by geometry finished
Creating geometry index on planet_osm_point
Creating indexes on planet_osm_roads finished
All indexes on planet_osm_roads created in 281s
Completed planet_osm_roads
Stopping table: planet_osm_nodes
Stopped table: planet_osm_nodes in 0s
Stopping table: planet_osm_ways
Building index on table: planet_osm_ways
Copying planet_osm_line to cluster by geometry finished
Creating geometry index on planet_osm_line
Creating osm_id index on planet_osm_point
Creating indexes on planet_osm_point finished
All indexes on planet_osm_point created in 3377s
Completed planet_osm_point
Stopping table: planet_osm_rels
Building index on table: planet_osm_rels
Stopped table: planet_osm_rels in 248s
Creating osm_id index on planet_osm_line
Creating indexes on planet_osm_line finished
All indexes on planet_osm_line created in 7877s
Completed planet_osm_line
Copying planet_osm_polygon to cluster by geometry finished
Creating geometry index on planet_osm_polygon
Creating osm_id index on planet_osm_polygon
Creating indexes on planet_osm_polygon finished
All indexes on planet_osm_polygon created in 14029s
Completed planet_osm_polygon
Stopped table: planet_osm_ways in 27579s

Osm2pgsql took 39891s overall
node cache: stored: 303408415(100.00%), storage efficiency: 50.25% (dense blocks: 1533, sparse nodes: 295593908), hit rate: 100.00%
+ sudo -u postgres psql -d gis -f indexes.sql
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
+ service postgresql stop
 * Stopping PostgreSQL 10 database server
   ...done.
+ exit 0

```

**Comment by Pr0gmaT1k** [comment]
I fugured out by extended the swap by 100GB. 15GB Ram, 15GB Swap + 100GB extension.
It appear to work but now I'm facing Hardware problem:
`DB writer thread failed due to ERROR: result COPY_END for planet_osm_nodes failed: ERROR:  could not extend file "base/16385/18035.152": No space left on device
HINT:  Check free disk space.`

**Comment by Istador** [comment]
> 500GB SSD - 115GB Swap - 10GB OS / Docker etc - 45GB planet.osm.pbf ± 300GB.
> I will add 1TB crossed_fingers

Yes, 300 GB seems to be too small for an Europe import.
I have imported Europe and Africa (very small compared to Europe), and the postgres database alone takes up over 400 GiB (+tiles, +docker images, +logfiles, etc).

**Comment by gareth-johnstone** [comment]
hi guys,

Im facing the same issue when importing europe

```
Reading in file: /data.osm.pbf
Using PBF parser.
Processing: Node(1854980k 485.6k/s) Way(0k 0.00k/s) Relation(0 0.00/s)/run.sh: line 63:   154 Killed                  sudo -u renderer osm2pgsql -d gis --create --slim -G --hstore --tag-transform-script /home/renderer/src/openstreetmap-carto/openstreetmap-carto.lua -C 2048 --number-processes ${THREADS:-4} -S /home/renderer/src/openstreetmap-carto/openstreetmap-carto.style /data.osm.pbf
+ sudo -u postgres psql -d gis -f indexes.sql
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
+ service postgresql stop
 * Stopping PostgreSQL 10 database server
   ...done.
+ exit 0

```

is the solution to increase the SWAP?

**Comment by BlackWolfDEsign** [comment]
> hi guys,
> 
> Im facing the same issue when importing europe
> 
> ```
> Reading in file: /data.osm.pbf
> Using PBF parser.
> Processing: Node(1854980k 485.6k/s) Way(0k 0.00k/s) Relation(0 0.00/s)/run.sh: line 63:   154 Killed                  sudo -u renderer osm2pgsql -d gis --create --slim -G --hstore --tag-transform-script /home/renderer/src/openstreetmap-carto/openstreetmap-carto.lua -C 2048 --number-processes ${THREADS:-4} -S /home/renderer/src/openstreetmap-carto/openstreetmap-carto.style /data.osm.pbf
> + sudo -u postgres psql -d gis -f indexes.sql
> CREATE INDEX
> CREATE INDEX
> CREATE INDEX
> CREATE INDEX
> CREATE INDEX
> CREATE INDEX
> CREATE INDEX
> CREATE INDEX
> CREATE INDEX
> CREATE INDEX
> CREATE INDEX
> CREATE INDEX
> CREATE INDEX
> + service postgresql stop
>  * Stopping PostgreSQL 10 database server
>    ...done.
> + exit 0
> ```
> 
> is the solution to increase the SWAP?
> 
> Also, to re-import is it just the case of re-running the same command again?

I'll take a look at my SWAP later. Maybe I will adjust the SWAP and let you know. (but I thought mine was big enough).

**Comment by Istador** [comment]
I only see output logs in this issue.

Can someone please post the exact command they are executing?

Is it just
```
docker run \
    -v /absolute/path/to/europe.osm.pbf:/data.osm.pbf \
    -v openstreetmap-data:/var/lib/postgresql/10/main \
    overv/openstreetmap-tile-server \
    import
```
or
```
docker run \
    -v /absolute/path/to/europe.osm.pbf:/data.osm.pbf \
    -v /absolute/path/to/europe.poly:/data.poly \
    -v /openstreetmap-data:/var/lib/postgresql/10/main \
    overv/openstreetmap-tile-server \
    import
```
or something different?

E.g. with additional options (`--shm-size`), environment variables (`THREADS`, `AUTOVACUUM`) or by using `docker-compose`?

---

Are you using the latest version of this project?

```
$ docker image inspect overv/openstreetmap-tile-server --format "{{println .Created}}"
2019-07-02T21:24:12.736883214Z
```

**Comment by BlackWolfDEsign** [comment]
i increased my swap and and it's further than before Node(1811730k). I'll write the current status tomorrow

if it crashes, i test your commands

**Comment by gareth-johnstone** [comment]
> I only see output logs in this issue.
> 
> Can someone please post the exact command they are executing?
> 
> Is it just
> 
> ```
> docker run \
>     -v /absolute/path/to/europe.osm.pbf:/data.osm.pbf \
>     -v openstreetmap-data:/var/lib/postgresql/10/main \
>     overv/openstreetmap-tile-server \
>     import
> ```
> 
> or
> 
> ```
> docker run \
>     -v /absolute/path/to/europe.osm.pbf:/data.osm.pbf \
>     -v /absolute/path/to/europe.poly:/data.poly \
>     -v openstreetmap-data:/var/lib/postgresql/10/main \
>     overv/openstreetmap-tile-server \
>     import
> ```
> 
> or something different?
> 
> E.g. with additional options (`--shm-size`), environment variables (`THREADS`, `AUTOVACUUM`) or by using `docker-compose`?
> 
> Are you using the latest version of this project?
> 
> ```
> $ docker image inspect overv/openstreetmap-tile-server --format "{{println .Created}}"
> 2019-07-02T21:24:12.736883214Z
> ```

I'm using the 2nd with the poly with autoupdates set to yes

**Comment by BlackWolfDEsign** [comment]
maybe **increasing the SWAP** works, Node(2309150k).

**Comment by BlackWolfDEsign** [comment]
it works, :) Processing: Node(2309151k 19.3k/s) Way(277k 0.02k/s) Relation(0 0.00/s)

**Comment by HuMonkey** [comment]
> it works, :) Processing: Node(2309151k 19.3k/s) Way(277k 0.02k/s) Relation(0 0.00/s)
> 
> https://wiki.ubuntuusers.de/Swap/

Hi, how did you solve the import error? I am also getting the same error.

**Comment by Istador** [comment]
> 
> 
> > it works, :) Processing: Node(2309151k 19.3k/s) Way(277k 0.02k/s) Relation(0 0.00/s)
> > https://wiki.ubuntuusers.de/Swap/
> 
> Hi, how did you solve the import error? I am also getting the same error.

By increasing the swap (aka. by increasing the virtual memory by using slower disk space for it).

This is a workaround, not a fix for the problem.

**Comment by stevo01** [comment]
I found following issue with discussion about semilar observations in osm2psql project: 
https://github.com/openstreetmap/osm2pgsql/issues/931
