### ISSUE TITLE
renderd.sock

### ISSUE THREAD

**Issue by mpele** [Overv/openstreetmap-tile-server#310]
I was just looking the code and noticed that the location of the renderd.sock is not consistent:

https://github.com/Overv/openstreetmap-tile-server/blob/25a661e3da27c1fc91d5b586eed09cb088f49ab9/openstreetmap-tiles-update-expire.sh#L194
https://github.com/Overv/openstreetmap-tile-server/blob/81c343305595fb8ae976dbbcf5a7fa2efd4093c1/apache.conf#L6

Is this a mistake?

**Comment by galewis2** [comment]
That's a great question, that would've happened when I migrated from compiled renderd to the one available in the Ubuntu 22.04 repos. I hadn't noticed an issue when making the PR and later use of this, so I don't know what the impacts are if any

**Comment by Istador** [comment]
The one in the `apache.conf` seems to be the new one.

If `render_expired` fails to communicate with `renderd` because of the wrong socket, then the tiles that were changed by the update might not get re-rendered and will instead keep their old content.

Any `"Expiry failed"` messages in the run log maybe?

**Comment by galewis2** [comment]
I'll have a look at this in the next couple days to see if there's any impacts that I missed.

**Comment by galewis2** [comment]
I struggled to see any errors, but I didn't notice any tiles get re-rendered. So I will just fix this and I will have someone else check it out because I certainly agree it should have issues

**Comment by galewis2** [comment]
So /var/run is symlinked to /run, so it should be inconsequential. But I will still make the fix for consistency!

**Comment by nielsole** [comment]
https://github.com/Overv/openstreetmap-tile-server/pull/314
