### ISSUE TITLE
Run tile-server as HTTPS server.

### ISSUE THREAD

**Issue by HTlee1990** [Overv/openstreetmap-tile-server#320]
First of all, Thank you guys nice project!

I want to run on my own tile-server in offline circumstances. 

And I want to run tile server as HTTPS , not HTTP. 
How can I do that..? 

I really need your help

**Comment by Istador** [comment]
Volume mount your TLS certificates into the docker container and adjust the `apache.conf` to use them to listen on port 443.

OR:
Use a separate proxy (e.g. encapsulated in its own docker container) that has the certificates and handles HTTPS, that then forwards the unencrypted traffic to the osm container.
Outdated Example: https://github.com/Overv/openstreetmap-tile-server/issues/19#issuecomment-466607919

**Comment by HTlee1990** [comment]
Thank you I used reverse-proxy like you said
