### ISSUE TITLE
Error when PostgreSQL 14 database start with latest image on Offline

### ISSUE THREAD

**Issue by HTlee1990** [Overv/openstreetmap-tile-server#321]
I am trying to upload map-tile-server container on offline circumstances.
What I did was 

**1. pull image on online Computer( mac )** 
I specified platform because offline architecture is linux/amd64.
* docker pull overv/openstreetmap-tile-server --platform=linux/amd64

2. create volume 

docker volume create osm-data

**2. Import as Below**

docker run \
    -v /Users/morph/project/please/south.osm.pbf:/data/region.osm.pbf \
    -v osm-data:/data/database/ \
    overv/openstreetmap-tile-server \
    import

4. change **mapdatas** in container into **tarfile**

docker run -it -v osm-data:/osm-data --name ${tempContainerName} ubuntu tar cvf /backup.tar /osm-data

**5. cp tarfile to local**

docker cp ${tempContainerName}:/backup.tar .

**6. save docker image into tarfile**

docker save -o overv.tar overv/openstreetmap-tile-server

**7. move tarImageFile and mapDatas copied in local to offline computer**

**8. load docker image**

docker load --input overv.tar

**9. run osm-tile-server with proxy server by docker-compose.yml**
docker-compose.yml file would be like below.
`version: "3.7"

services:

  proxy:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./frontend/key/mc.chained.crt:/etc/nginx/conf.d/mc.chained.crt
    - ./frontend/key/mc.key:/etc/nginx/conf.d/mc.key
    ports:
    - "9898:443"
    depends_on:
    - osm
    restart: always

  osm:
    image: overv/openstreetmap-tile-server
    volumes:
    - /Users/morph/osm-data:/data/database/
    ports:
      - "9899:80"
    restart: always
    command: "run"
`

**### 10. ERROR OCCUR!**
**proxy server works fine**, but map-tile-server container spit below errors and kept restarting and die eventually.

**Error** is like this.

listen_addresses = '*'
autovacuum = on
+ service postgresql start
 * Starting PostgreSQL 14 database server
 * Error: /usr/lib/postgresql/14/bin/pg_ctl /usr/lib/postgresql/14/bin/pg_ctl start -D /var/lib/postgresql/14/main -l /var/log/postgresql/postgresql-14-main.log -s -o  -c config_file="/etc/postgresql/14/main/postgresql.conf"  exited with status 1:
popen failure: Cannot allocate memory
The program "postgres" is needed by pg_ctl but was not found in the
same directory as "/usr/lib/postgresql/14/bin/pg_ctl".
Check your installation.
   …fail!
   
   
I don't know what I did wrong... 
Please... Help me guys. 

Really Appreciate you guys nice work and helps in advance. Thank you.

**Comment by DariaZhdanova-dev** [comment]
@HTlee1990 Did you managed this issue? I have enough RAM, but still the error persists
