### ISSUE TITLE
Rendering retina tiles

### ISSUE THREAD

**Issue by dennisbos84** [Overv/openstreetmap-tile-server#33]
The tile server doesn't seem to render high res retina tiles: /tile/18/134637/86148@2x.png

**Comment by Overv** [comment]
It looks like this requires a modification to the map style: https://gis.stackexchange.com/a/190009/34626

In this case it's a matter of changing the scale on this line to `2`:

https://github.com/gravitystorm/openstreetmap-carto/blob/d330a987c7e2a814fc2997dad495270a0c079bac/project.mml#L1

**Comment by MaRaSu** [comment]
No need to modify map style and you can serve both normal & high res (retina) tiles at the same time. What you need to do is to edit renderd.conf and add an entry for high res tiles. Example below for high res section that I added:

```
[map_retina]
URI=/tiles@2x/
TILEDIR=/var/lib/mod_tile
XML=/home/renderer/src/map/mapnik.xml
HOST=localhost
MAXZOOM=19
SCALE=2.0
TILESIZE=512
```

I did not figure out how you could serve high res tiles with the usual `...{y}@2x.png` file naming convention but having a distinct URI path for high res works as well for most cases.

**Comment by Naahuel** [comment]
@MaRaSu sorry to bring up such an old thread. I did that modifying the dockerfile to add those lines at the end of renderd.conf but now the old url (/tile/) doesn't work, just the retina one.

I can't figure it out! what did I miss?

**Comment by gsontheimer** [comment]
I also would like to use retina tiles - but as a beginner I do not understand where to edit this renderd.conf file.

Can you please give me a more detailed instruction?

**Comment by Istador** [comment]
It is located at: `/usr/local/etc/renderd.conf`

https://github.com/Overv/openstreetmap-tile-server/blob/5572c9722ef7cc478d0143436b9f723c54171527/run.sh#L184

You should be able to volume mount your own modified file onto that path or edit it with a Dockerfile. See #154 for more details.
