### ISSUE TITLE
Pre-render No map for: ajt

### ISSUE THREAD

**Issue by Kofl** [Overv/openstreetmap-tile-server#332]
Hi,

I am using the latest image with full world import.

If I try to pre-render via

> c=$(docker ps | grep "overv/openstreetmap-tile-server" | grep -Eo "^[0-9a-f]+")
> docker exec -it "$c"  render_list  -a  -f  -m ajt  -z 0  -Z 10

docker logs show:

> map_1  | ** (process:130): ERROR **: 09:29:00.835: No map for: ajt

And pre-rendering outputs immediately:

> Rendering client
> Starting 1 rendering threads
> Rendering all tiles from zoom 0 to zoom 10
> Rendering all tiles for zoom 0 from (0, 0) to (0, 0)
> Rendering all tiles for zoom 1 from (0, 0) to (1, 1)
> Rendering all tiles for zoom 2 from (0, 0) to (3, 3)
> Rendering all tiles for zoom 3 from (0, 0) to (7, 7)
> Rendering all tiles for zoom 4 from (0, 0) to (15, 15)
> Rendering all tiles for zoom 5 from (0, 0) to (31, 31)
> Rendering all tiles for zoom 6 from (0, 0) to (63, 63)

and then hangs. Thanks for any input.

docker-compose.yml

```
version: '3'
services:
map:
image: overv/openstreetmap-tile-server:2.2.0
environment:
- THREADS=16
- OSM2PGSQL_EXTRA_ARGS=--flat-nodes /data/tiles/flat_nodes.bin -C 2000
ports:
- "80:80"
volumes:
- /opt/osm-tiles/planet-latest.osm.pbf:/data/region.osm.pbf
- osm-data-sql:/data/database/
- osm-tiles:/data/tiles/
- /opt/openstreetmap-carto-modified:/data/style/
command: "run"
volumes:
osm-data-sql:
external: true
osm-tiles:
external: true
```

**Comment by Istador** [comment]
That changed with version [v2.1.0](https://github.com/Overv/openstreetmap-tile-server/releases/tag/v2.1.0):
The map is no longer called `ajt` but `default`. This should allow you to leave the `-m ajt` argument out (`default` should be the default for `render_list` when `-m` is not specified).

**Comment by Kofl** [comment]
Thanks, that fixed it.
