### ISSUE TITLE
gcc-12-base:amd64.list: invalid argument. | Docker-issue or image issue?

### ISSUE THREAD

**Issue by TheSwede86** [Overv/openstreetmap-tile-server#338]
Hello,

Recently moved my Docker-dir to an external harddrive since running the "import" caused my last computer to run out of space.
However then it worked (it started to import) - Debian 11 w. docker-data-dir "as-is" - and now I get this error when trying to run;
```
docker run \
    -v "/media/my-user/Intenso 1TB USB 3.0/OpenStreetMap Maps/europe-latest.osm.pbf":/data/region.osm.pbf \
    -v osm-data:/data/database/ \
    overv/openstreetmap-tile-server \
    import
```
```
docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: open /var/lib/dpkg/info/gcc-12-base:amd64.list: invalid argument.
```

Is this related to my Docker setup (e.g. I moved my Docker data-dir to my external harddrive) or might this be caused by the image?

Please see:
https://forums.docker.com/t/gcc-12-base-amd64-list-error-related-to-moving-docker-data-dir/130630
for a more detailed post.

Best Regards - TheSwede86

**Comment by nielsole** [comment]
This is related to your docker setup.
