### ISSUE TITLE
How to use this in production?

### ISSUE THREAD

**Issue by srudin** [Overv/openstreetmap-tile-server#361]
So there are these import and run processes. I have been able to execute the import and I have been able to execute the run process and I did get the map tiles as expected.

However if I re-execute the import process I get "ERROR: role renderer already exists". And if I re-execute the run process I get "ERROR: role renderer does not exist". I have set UPDATES to enabled and configured a persistent volume for both data/database and data/tiles.

Now I wonder how this is supposed to be used in production mode. What if for whatever reason the container needs to be restarted? I always need to delete everything first, then execute the import and then the run process again? There has to be a way to keep the data I assume - what am I missing?

**Comment by srudin** [comment]
Hm, seems like there was an error after re-executing the run process. It does work now, sorry for that.

So is it correct then that the import process is supposed to be executed once only (UNLESS you want to change the region/poly)? And the run process is supposed to be run again and again and with UPDATES enabled it will always serve the newest tiles?

**Comment by Istador** [comment]
> So is it correct then that the import process is supposed to be executed once only (UNLESS you want to change the region/poly)?

Yes.

> And the run process is supposed to be run again and again and with UPDATES enabled it will always serve the newest tiles?

Yes, if the `UPDATES` were enabled during the initial `import` too.

**Comment by srudin** [comment]
Ok perfect thx!
