### ISSUE TITLE
No import file at /data.osm.pbf

### ISSUE THREAD

**Issue by qingtongq** [Overv/openstreetmap-tile-server#382]
+ echo 'WARNING: No import file at /data.osm.pbf, so importing Luxembourg as example...'
+ wget -nv http://download.geofabrik.de/europe/luxembourg-latest.osm.pbf -O /data.osm.pbf
WARNING: No import file at /data.osm.pbf, so importing Luxembourg as example...

**Comment by qingtongq** [comment]
root@twmapserv1:~# cd /home/renderaccount/zambia-latest.osm.pbf
root@twmapserv1:/home/renderaccount/zambia-latest.osm.pbf# ll
总计 8
drwxr-xr-x 2 root root 4096  8月  3 10:50 ./
drwxr-xr-x 3 root root 4096  8月  3 14:33 ../
root@twmapserv1:/home/renderaccount/zambia-latest.osm.pbf# ^[[200~time docker run -v /home/renderaccount/zambia-latest.osm.pbf:/data.osm.pbf -v openstreetmap-data:/var/lib/postgresql/12/main overv/openstreetmap-tile-server:1.3.10 import~

**Comment by qingtongq** [comment]
`root@twmapserv1:~# cd /home/renderaccount/zambia-latest.osm.pbf
root@twmapserv1:/home/renderaccount/zambia-latest.osm.pbf# ll
总计 8
drwxr-xr-x 2 root root 4096  8月  3 10:50 ./
drwxr-xr-x 3 root root 4096  8月  3 14:33 ../
root@twmapserv1:/home/renderaccount/zambia-latest.osm.pbf# ^[[200~time docker run -v /home/renderaccount/zambia-latest.osm.pbf:/data.osm.pbf -v openstreetmap-data:/var/lib/postgresql/12/main overv/openstreetmap-tile-server:1.3.10 import~
`

**Comment by nielsole** [comment]
`/data.osm.pbf` must be a file, not a directory. If you can `cd` into `zambia-latest.osm.pbf` it is a directory.

**Comment by Istador** [comment]
Also keep in mind that the `1.3.10` version that you are using is over 3 years old.
