### ISSUE TITLE
error in script openstreetmap-tiles-update-expire

### ISSUE THREAD

**Issue by stevo01** [Overv/openstreetmap-tile-server#39]
vpithart reportet error in file /usr/bin/openstreetmap-tiles-update-expire: Line 153: /usr/bin/openstreetmap-tiles-update-expire: /var/lib/mod_tile/data.poly: Permission denied

see https://github.com/Overv/openstreetmap-tile-server/commit/a9392359b93fedb4a67607432d2a43868f534911#commitcomment-34152117 for details

**Comment by stevo01** [comment]
solution: remove Line 153

**Comment by Overv** [comment]
Fixed by #41
