### ISSUE TITLE
Postgres in container not working

### ISSUE THREAD

**Issue by Manoj-py** [Overv/openstreetmap-tile-server#413]
i was deploying the image in kubernetes and it enters into CrashLoopBackOff with this error

 + service postgresql start                                                                                                                                 
* Starting PostgreSQL 15 database server                                                                                                                  
 * Error: /usr/lib/postgresql/15/bin/pg_ctl /usr/lib/postgresql/15/bin/pg_ctl start -D /var/lib/postgresql/15/main -l /var/log/postgresql/postgresql-15-main.log -s -o  -c config_file="/etc/postgresql/15/main/postgresql.conf"  exited with status 1:                                                              
pg_ctl: directory "/var/lib/postgresql/15/main" is not a database cluster directory   ..fail!

**Comment by Manoj-py** [comment]
figured it out

**Comment by ghost** [comment]
> figured it out

how did you solve the issue im getting the same error :(
