### ISSUE TITLE
Error downloading tile file : i/0 time out

### ISSUE THREAD

**Issue by Manoj-py** [Overv/openstreetmap-tile-server#416]
i am running the overv/openstreetmap-tile-server on kubernetes and i have donwloaded the india.osm.pbf file and the pods and the deployment are running ok no error no crashes... and service is also been properly configured but when ever my other ser ice requests for a tile it takes lot of time and at last i get the error saying "Error downloading tile file: Get "http://overv-service/tile/15/23454/15104.png": dial tcp 172.20.83.213:80: i/o timeout"... and i also tried entering it pod and run "render_list -all" for prerendering it gets stuck with the below thing:
Rendering client
Starting 1 rendering threads
Rendering all tiles from zoom 0 to zoom 20
Rendering all tiles for zoom 0 from (0, 0) to (0, 0)
Rendering all tiles for zoom 1 from (0, 0) to (1, 1)
Rendering all tiles for zoom 2 from (0, 0) to (3, 3)
Rendering all tiles for zoom 3 from (0, 0) to (7, 7)
Rendering all tiles for zoom 4 from (0, 0) to (15, 15)
Rendering all tiles for zoom 5 from (0, 0) to (31, 31)
Rendering all tiles for zoom 6 from (0, 0) to (63, 63)  can anyone help me with this pls i need the k8s deployment to give tiles as sson as possible or any other way to fix this issue?

**Comment by Manoj-py** [comment]
i started to see the demo leaftlet which shows whole of the map in root path then i found this error in the logs of the deployments 
"failed to render TILE default 5 16-23 16-23"
"failed: FATAL:  could not open file "global/pg_filenode.map": Input/output error"

**Comment by Evaia** [comment]
looks to me like there was a problem with your import or the database isn't running/reachable.

**Comment by Manoj-py** [comment]
this is inside the k8s cluster the issues is when i am  trying to get map from the services it isn't serving the map and gives this error if i am using the public ip the it gives tiles
