### ISSUE TITLE
Automatize tile rendering of big country

### ISSUE THREAD

**Issue by iaguerri** [Overv/openstreetmap-tile-server#422]
Hello!

I'm setting up an OpenStreetMap tile server on Kubernetes. I have an external database loaded with data from Spain. I've deployed the pods in the Kubernetes cluster and established PVCs for data/database and data/tiles to store the tiles permanently. My goal is to use this tile server in iOS and Android apps for a transportation application.

However, I'm facing an issue where I need to manually navigate the map, zooming in and out to load the tiles. The PVC is storing the tiles, so this is not a problem. But, this process is cumbersome and needs to be automated, as manually covering the entire country at different zoom levels is labor-intensive and tedious.

Is there any kind of script to automatize all the tile rendering?

Thanks in advance! 😄

**Comment by Istador** [comment]
Search for `render_list_geo.pl` and/or `render_list`.

There are examples in the issues of this project (some are old though - don't provide `-m ajt` as an argument anymore).

**Comment by iaguerri** [comment]
Hey Robin!
Yes, with a command like this: 
`docker exec -it "$c"  ./render_list_geo.pl -f -z 11 -Z 18 -x -0.64  -y 39.16 -X 0.19 -Y 39.67` works

Thanks!
