### ISSUE TITLE
Renderd logs not visible in k8s container

### ISSUE THREAD

**Issue by Manoj-py** [Overv/openstreetmap-tile-server#425]
i am running the docker image in kubernetes for some tiles rendering i get 404 error dond exactly what is the error when i see the container logs i cannot see anything after

INFO: 17:40:13.258: Running in foreground mode...                                                                                                                          
INFO: 17:40:13.258: Loading parameterization function for                                                                                                                  
INFO: 17:40:13.258: Loading parameterization function for                                                                                                                   
INFO: 17:40:13.258: Loading parameterization function for                                                                                                                  
INFO: 17:40:13.260: Loading parameterization function for                                                                                                                   
Mapnik LOG> 2024-05-23 17:42:25: SVG PARSING ERROR:"SVG support error: <enable-background> attribute is not supported"                                                         
Mapnik LOG> 2024-05-23 17:42:26: SVG PARSING ERROR:"SVG support error: <enable-background> attribute is not supported"

want to see renderd logs as weel how to do it ?

**Comment by Istador** [comment]
Afaik that is the output of the `renderd` process running.

https://github.com/Overv/openstreetmap-tile-server/blob/6088b9b37f440f141f643f413a3d6454a1c01aa2/run.sh#L189

**Comment by Manoj-py** [comment]
i want to see the logs of requests coming for the container and response given by the server and also want to see why is that error generating how to find that logs

**Comment by Istador** [comment]
The log of HTTP requests with the returned HTTP status code would be the Apache access log, not the renderd log.

Hmm, in theory that should be configured to go to the output too:
https://github.com/Overv/openstreetmap-tile-server/blob/6088b9b37f440f141f643f413a3d6454a1c01aa2/Dockerfile#L112-L113

But in practice that seems to be not working and linking to `/dev/stdout` seems to be a misconfiguration, see https://github.com/moby/moby/issues/19616
(The symlink of `/dev/stderr` for the Apache error log seems to be working and appears in the docker log.)

Though seeing that access log won't help you much. It doesn't give you any info what is wrong, but just what paths were accessed when by whom and what the HTTP status code was.

**Comment by Manoj-py** [comment]
right now there was permission issues of root and renderd with the tables fixed it all that i want is to see the logs of http request and response the stated issue is fixed...
