### ISSUE TITLE
HTTP 503 after install and import

### ISSUE THREAD

**Issue by gareth-johnstone** [Overv/openstreetmap-tile-server#43]
As the title says, I've ran through the docker setup, imported a osm.pbf.

issued the run command and when i go to my IP address im getting a HTTP 503

Any ideas?

**Comment by Overv** [comment]
What do the container logs show?

**Comment by gareth-johnstone** [comment]
Im new to docker!

Where does one find such a thing? :)

**Comment by BlackWolfDEsign** [comment]
https://docs.docker.com/engine/reference/commandline/logs/

**Comment by stevo01** [comment]
some commands that I used for verification of tile server:

the following command shows log file output from docker container:
`docker logs -f CONTAINER`

the following url shows statistics from mod_tile:
`http://localhost:80/mod_tile`

download of single tile:
`http://localhost:80/tile/9/277/170.png`

**Comment by gareth-johnstone** [comment]
`root@osm:/home# docker run -p 80:80 \
> -e THREADS=7 \
> -v openstreetmap-data:/var/lib/postgresql/10/main \
> -v openstreetmap-rendered-tiles:/var/lib/mod_tile \
> -d overv/openstreetmap-tile-server \
> -e UPDATES=false \
> run
28ea7f6b73cb5572c2b177fd72ff36514f7d2e18b5863b0b1c9f69862be00967
root@osm:/home# ^C
root@osm:/home# docker logs -f 28ea7f6b73cb5572c2b177fd72ff36514f7d2e18b5863b0b1c9f69862be00967
+ '[' 3 -ne 1 ']'
usage: <import|run>
commands:
    import: Set up the database and import /data.osm.pbf
    run: Runs Apache and renderd to serve tiles at /tile/{z}/{x}/{y}.png
environment variables:
    THREADS: defines number of threads used for importing / tile rendering
    UPDATES: consecutive updates (enabled/disabled)
+ echo 'usage: <import|run>'
+ echo commands:
+ echo '    import: Set up the database and import /data.osm.pbf'
+ echo '    run: Runs Apache and renderd to serve tiles at /tile/{z}/{x}/{y}.png'
+ echo 'environment variables:'
+ echo '    THREADS: defines number of threads used for importing / tile rendering'
+ echo '    UPDATES: consecutive updates (enabled/disabled)'
+ exit 1
root@osm:/home#
`

Here is the command i ran, and then fetching the "log" from that

**Comment by Istador** [comment]
The syntax of the [docker run](https://docs.docker.com/engine/reference/run/) command goes:
```
docker run [OPTIONS] IMAGE[:TAG|@DIGEST] [COMMAND] [ARG...]
````

If I'm not mistaken, the `-e UPDATES=false` is an option and have to come before the image

```bash
docker run -d -p 80:80 \
  -e THREADS=7 \
  -e UPDATES=false \
  -v openstreetmap-data:/var/lib/postgresql/10/main \
  -v openstreetmap-rendered-tiles:/var/lib/mod_tile \
  overv/openstreetmap-tile-server \
  run
```

This seems to be wrong in the [README.md](https://github.com/Overv/openstreetmap-tile-server/blob/2be4107bb1fb3193f1151d92d6f4b80d7a7cbb72/README.md#enabling-automatic-updating-optional) file (Line 71).
