### ISSUE TITLE
Introduce versioning

### ISSUE THREAD

**Issue by Istador** [Overv/openstreetmap-tile-server#45]
Please add version number tags to docker images pushed to [docker hub](https://hub.docker.com/r/overv/openstreetmap-tile-server), so that it's possible to use older versions by referring to a specific version of the image, instead of always using `latest`.

Building upon `latest` is problematic for users of the image, because it isn't reproducible over time. Newer versions might introduce breaking changes or changes to the performance that might favor one setup over another. Depending on when the image was pulled, `latest` refers to different images on different machines.

Users inexperienced with docker might forget to `docker pull` when they want to use the newest `latest` version. Advocating the use of specific version numbers allows them to easily recognize that they are using an outdated version and that they might want to upgrade it when facing errors.

https://blogs.msdn.microsoft.com/stevelasker/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/

---

The same version numbers should also be used in this repository (e.g. as tags added to the commits), so that it's traceable from which commit the image was build from.

Downside of using git tags: Github automatically interprets them as "releases".

---

Optionally, this could even be done retroactively for old versions of this repository, but would require building and pushing those old images again.

**Comment by Overv** [comment]
I've partitioned the current history into a couple of different milestones and pushed versioned tags/images for them.

**Comment by Istador** [comment]
Nice anecdote regarding this.

On our productive server, a colleague of mine pulled the newest image version and throw away the old one that we were using. He wondered why it wasn't starting anymore, and figured based on error messages, that it was because of postgres 10/12. So he changed a few lines by me that were still referring to 10. The service seemed to run then and served tiles, except, unknown to him, that the rendering wasn't working anymore. A day later the amount of errors due to the client render requests overloaded the docker service.

I was able to pull the `1.0` tag from the docker hub, but because it was builded over a year after the time when 59068928e6a343c8872af27b89460b1c6ece7a84 was around as `latest`, almost all of the software packages inside of the image had altered. Due to changes to `openstreetmap-carto` in that time, we can't use our custom `mapnik.xml` anymore with the `1.0` image and have to adjust/redo all of our customizations with a newer version.

That's not your fault, but mine. I should have pushed the image that we were using to our own private docker repository for safekeeping. Remember: never use `latest`.
