### ISSUE TITLE
Is it possible to add WMTS capabilities to this server

### ISSUE THREAD

**Issue by smac89** [Overv/openstreetmap-tile-server#47]
I have just set up my server and it is working great. Now I'm wondering if it is possible to extend this server to be used as WMTS? Can you give suggestions or a guide that describes the process?

I see someone [here](https://github.com/osmlab/wmts-osm) has something like that done, but I'm not sure how to configure that file to work with this server

**Comment by smac89** [comment]
Got it.
I used this website: http://wmts.maptiler.com/

When I supplied the url to the server's xyz format, I got back both the link to a tileJSON and WMTSCapabilities file.
Example link: `http://[your_server]:[port]/tile/{z}/{x}/{y}.png`

**Comment by smac89** [comment]
Another alternative I found and settled on is to use mapproxy. I found a docker image here:
https://github.com/yagajs/docker-mapproxy

Mapproxy automatically adds wmts capabilities to the tile server while also acting as cache for the requested tiles. This IMO is the best solution

**Comment by Istador** [comment]
> [...] while also acting as cache for the requested tiles. This IMO is the best solution

When you are using it as a proxy or as an replication mechanisms to scale the service, ergo running it on another server, then yes, this seems like a good solution.

Otherwise it's a cache in-front of an already dynamic and efficient cache (mod_tile).
Is it possible to disable the caching behavior (e.g. when run on the same host as the renderer)?

**Comment by smac89** [comment]
@Istador I don't immediately see a way of disabling the caching behaviour of `mod_tile`, but I believe you can disable `mapproxy`'s cache in the configuration file and just serve tiles directly from your configured tile source.

Since I'm just using this as a quick fix for the application I was writing and the map area I use is very small, I have not looked much deeper into fixing the duplicate caching. I wonder if there is a way to configure mapproxy to use `mod_tile`'s postgis database which is available as a docker volume.
