### ISSUE TITLE
Multi Language Tile Server

### ISSUE THREAD

**Issue by singhyadvendra** [Overv/openstreetmap-tile-server#49]
I am currently trying to setup a multi language tile server. do you have any ideas to support that

**Comment by Istador** [comment]
One postgresql database and renderer, but with several different openstreetmap-carto map styles using it. Each style is individualized for the target language, e.g. as described in issue #24.

This docker image has only one map style active with the key `ajt`. But the software it uses (mod_tile / renderd) should support several different styles at once (defined in [renderd.conf](https://github.com/SomeoneElseOSM/mod_tile/blob/master/renderd.conf)). So you might only need to exchange a (few) config file(s), and copy several styles into the container (referenced in the config file).

**Comment by singhyadvendra** [comment]
I have tried the changes but it seems to me that my changes in **rendered.conf** are not correct. somehow missing something there

**Comment by singhyadvendra** [comment]
Hi Istador 
I am getting error for the following code
An error occurred while loading the map layer 'style_fr': Postgis Plugin: ERROR:  column "tags" does not exist
LINE 3:     COALESCE(tags->'name:fr', tags->'name:nl', name, '') as ...

**Comment by Istador** [comment]
Without the full query or your Mapnik XML it's hard to tel exactly where and why this is happening.

Keep in mind / be aware of that there are some multi-layered queries in the default style. You only have access to the `tags` on the table inside the innermost sub query that is working on the table directly.

Yes:
```sql
SELECT COALESCE(...) AS name, ...
FROM tablename
```

No:
```sql
SELECT COALESCE(...) AS name, ...
FROM (SELECT name, ... FROM tablename))
```

---

E.g. a situation like that:
```sql
SELECT name, ...
FROM (SELECT name, ... FROM tablename))
```

Becomes:
```sql
SELECT name, ...
FROM (SELECT COALESCE(...) AS name, ... FROM tablename))
```

Or alternatively:
```sql
SELECT COALESCE(...) AS name, ...
FROM (SELECT name, tags, ... FROM tablename))
```

**Comment by singhyadvendra** [comment]
Hi Istador,

My Tile Server is working correctly displaying names as required.
Thanks for the help.

I have work on two more things. 
1. automatic updates of tile for a BBOX  PBF from EUROPE
2. preloading tiles

if you have any suggestions

Thanks Again
