### ISSUE TITLE
request for flatnode support

### ISSUE THREAD

**Issue by stevo01** [Overv/openstreetmap-tile-server#53]
The osm2psql application allows usage of flatnodes. Extract from manual:
```       
-F|--flat-nodes  Specifies the flat file to use to persistently store node information in slim mode
instead of in PostgreSQL. This file is a single > 40Gb large file. Only recommended for full planet
imports. Default is disabled.
```
The usage of this flag is a candidate for performance improvement. Additional its seems to be a workaround for the out of memory problems reportet here [Issue 931](https://github.com/openstreetmap/osm2pgsql/issues/931) and here [Issue31](https://github.com/Overv/openstreetmap-tile-server/issues/31).

**Comment by Overv** [comment]
I've added a way to enable osm2pgsql options in general, including `--flat-nodes`.

**Comment by stevo01** [comment]
Thanks! I made a import of full planet with flatnode option last days. Here are the results:  
- time for processing is around 32 hour for full import (instead 41 hour)
- the size of docker volumes for db is 762GB for database and 53 GB for flatnode files (instead 1,1GB)
- the peak RAM memory consumption was around 25GByte (instead 64GByte + 50GByte SWAP)

**Comment by Overv** [comment]
Great, thanks for the info!
