### ISSUE TITLE
Clearly update method

### ISSUE THREAD

**Issue by spearox** [Overv/openstreetmap-tile-server#54]
Dear contributors,

How the update works?
Every time if I update the pbf and poly file I need to stop and delete everyting expect of the generated tiles and run the „import” then the „run” task with the UPDATES=enabled env variable?

I now use thees commands to run.
```
docker run --rm -v /opt/openstreetmap/hungary-latest.osm.pbf:/data.osm.pbf -v /opt/openstreetmap/hungary.poly:/data.poly -v openstreetmap-data:/var/lib/postgresql/10/main overv/openstreetmap-tile-server import

docker run -p 80:80 -e UPDATES=enabled -v openstreetmap-data:/var/lib/postgresql/10/main -v openstreetmap-rendered-tiles:/var/lib/mod_tile -d overv/openstreetmap-tile-server run
```

**Comment by stevo01** [comment]
Hi,
the environment variable "UPDATES" allows you to enable the a periodical update which is running in background. 

note: you missed the options "-e UPDATES=enabled" and "-v openstreetmap-rendered-tiles:/var/lib/mod_tile" during import. Both are required to prepare the periodical update in directory "/var/lib/mod_tile/.osmosis". 

Here are some useful commands for debugging of the update feature:

## connect to docker container shell 
`docker exec -i -t openstreetmap-tile-server /bin/bash`

## show` replication timestamp of your importet database
```
root@360039daaf97:/home/renderer/src/openstreetmap-carto# cat  /var/lib/mod_tile/replication_timestamp.txt 
2019-09-01
```
## show configuration of osmosis
```
cat /var/lib/mod_tile/.osmosis/configuration.txt 
# The URL of the directory containing change files.
baseUrl=https://planet.openstreetmap.org/replication/minute

# Defines the maximum time interval in seconds to download in a single invocation.
# Setting to 0 disables this feature.
maxInterval = 3600
```
## show logfile / replag
```
root@5f55bf46f268:/home/renderer/src/openstreetmap-carto# tail -f /var/log/tiles/run.log 
[2019-09-16 19:40:01] 19514 start import from seq-nr 3674571, replag is 1 minute(s)
[2019-09-16 19:40:01] 19514 downloading diff
[2019-09-16 19:40:02] 19514 filtering diff skipped
[2019-09-16 19:40:02] 19514 importing diff
[2019-09-16 19:40:10] 19514 expiring tiles
[2019-09-16 19:40:11] 19514 Done with import
[2019-09-16 19:41:01] 19810 start import from seq-nr 3674572, replag is 1 minute(s)
[2019-09-16 19:41:01] 19810 downloading diff
[2019-09-16 19:41:02] 19810 filtering diff skipped
[2019-09-16 19:41:02] 19810 importing diff
[2019-09-16 19:41:07] 19810 expiring tiles
[2019-09-16 19:41:07] 19810 Done with import
```

**Comment by spearox** [comment]
Dear @stevo01,

Thanks for you help! I'll checked it. The update works!
