### ISSUE TITLE
Deploy application to kubernetes

### ISSUE THREAD

**Issue by Pflegusch** [Overv/openstreetmap-tile-server#56]
Is there an easy and straightforward way to deploy the application to kubernetes? I've been playing around with kompose and kompose convert but dont have any success. Can anyone help or has tips? 
Would be nice to have a helm chart in the future to make deploying as easy as possible and I would like to help with that, I'm still relatively new to Kubernetes/Docker and still learning a lot but would like to contribute.

Any help is appreciated :)

**Comment by ihadeed** [comment]
- create a VolumeClaim to hold the map data
- run a Deployment with that VolumeClaim mounted, let this Deployment handle the data import
- run another Deployment with a modified Dockerfile that wraps this one. It should wait until the first Deployment has ran and exited, before running the server.. just need to make sure they're in the same namespace
- you can then create a cronjob to update your data, or just enable auto updates via the environment variable 

If this image lets you serve & import data at the same time, then you don't need that wrapper with the wait functionality, you can deploy everything at once. Just need to set `restart: never` on the import Pod.

**Comment by MaRaSu** [comment]
Writing Helm chart & yaml to deploy openstreetmap-tile-server is relatively straightforward once you get your head around kubernetes basic concepts. It's a bit steeper hill to climb than trying to just convert Docker compose files, however not sure how much success you will have in debugging any kubernetes issues if you do not spend time mastering the basics.

Where the difficulty was in deploying tile server was in how kubernetes (storage) volumes handling differs from Docker. Forked this repo and added couple of tweaks to Dockerfile + run.sh to handle those.
