### ISSUE TITLE
Docker hub latest tag has no corresponding non-latest tag

### ISSUE THREAD

**Issue by mfotzler** [Overv/openstreetmap-tile-server#57]
Hello,

This image is wonderful. THANK YOU.

I'm building a docker image off of this one (I want to add render_list_geo.pl and meta2tile for pre-rendering a set of tiles based on lat/long range).

https://hub.docker.com/r/overv/openstreetmap-tile-server/tags shows latest was updated 4 days ago, but no other tag matches that modification date. I'd like to pin my Dockerfile to a specific version rather than latest.

Would you add a specific version tag in the hub for the new changes?

Thanks,
Matt

**Comment by Overv** [comment]
Done. However, I'm not quite sure how to version this kind of project properly since semantic versioning doesn't feel like a good match.

**Comment by mfotzler** [comment]
Thanks!

Yeah, from my point of view as a user, the most important part would be that newer version tags are clearly "greater than" older version tags. Some alternatives to semantic versioning that would satisfy that:

* Release number that increases with each push (1, 2, 3, ...)
* date stamp + incrementing build number for the day (2019-09-04-001)
