### ISSUE TITLE
Wrong log path for apache

### ISSUE THREAD

**Issue by vepito** [Overv/openstreetmap-tile-server#61]
In Dockerfile you wrote

RUN ln -sf /proc/1/fd/1 /var/log/apache2/access.log \
  && ln -sf /proc/1/fd/2 /var/log/apache2/error.log

Apache cannot start on my ubuntu18.04 system because the /proc/1 path does not exists.

According to https://docs.docker.com/v17.09/engine/admin/logging/view_container_logs/ the right log path is starting with /prof/self.

And I confirm this works fine on my system.

**Comment by Overv** [comment]
Fixed in b82e37b thanks to your link.
