### ISSUE TITLE
usage of tirex instead of renderd

### ISSUE THREAD

**Issue by stevo01** [Overv/openstreetmap-tile-server#67]
At the moment I am working on tile server for [open sea map](http://map.openseamap.org/) project based on Overv/openstreetmap-tile-server. The tile server is running now and initial import of osm world database is done. At the moment I am looking for a solution of the memory problem of renderd which another user reportet here:  https://github.com/Overv/openstreetmap-tile-server/issues/27

In parallel I am thinking about a switch from renderd to [tirex ](https://github.com/openstreetmap/tirex) instead to "riding dead horse".

Here the pros and cons from my point of view:
- tirex seems to be better documented (https://wiki.openstreetmap.org/wiki/Tirex)
- maintenence for tirex is still in progress, renderd seems to be unmaintened 
- fancy status view
- Tirex is in "production" use at tile.openstreetmap.de

Overv:
- have you worked with tirex in past and collected some first impressions?
- are there plans from your site to make tirex solutions available in the docker container?

**Comment by Overv** [comment]
I haven't had any experience with tirex yet. I have no preference one way or another, but you bring up some compelling arguments for favoring it over renderd.

Unfortunately I don't have time to look into this myself so there are currently no plans from my side to possibly make a switch for this container. For me it was always about just sticking to the recommended setup documented on switch2osm.org.
