### ISSUE TITLE
Connect to postgresql inside the container

### ISSUE THREAD

**Issue by kerimsari** [Overv/openstreetmap-tile-server#68]
Hi,

Is that possible to connect to postgresql instance from pgadmin or command line?

I saw that port 5432 is open but unmapped inside the container. I've mapped it to some ports on 192.168.99.100, but not able to connect to the instance via pgadmin or command line..

Please suggest..

Thank you
Kerim

**Comment by Overv** [comment]
This has been fixed in version 1.3.2, see the [new section in the README](https://github.com/Overv/openstreetmap-tile-server#connecting-to-postgres).

**Comment by kerimsari** [comment]
This time i am getting below error 

Reading in file: /data.osm.pbf
Using PBF parser.
node cache: stored: 0(-nan%), storage efficiency: -nan% (dense blocks: 0, sparse nodes: 0), hit rate: -nan%
Osm2pgsql failed due to ERROR: Read failed: Is a directory

I've read this post https://github.com/Overv/openstreetmap-tile-server/issues/8

The file that i want to import is exactly where it should be. So that is not the case for me..

Please suggest
Thank you very much.
Kerim

**Comment by Istador** [comment]
Please post the exact command that you executed that resulted in the error (`docker run [...]`).

Did you confirm the location of the file on your host computer or inside of the docker image?

Are you using Windows?

**Comment by kerimsari** [comment]
docker run -v /Users/kerim/Docker/turkey-latest.osm.pbf:/data.osm.pbf -v openstreetmap-data:/var/lib/postgresql/10/main overv/openstreetmap-tile-server import

Attached you have the proof.

I am using Mac OS Mojave

![image](https://user-images.githubusercontent.com/2835912/65668389-4c129a00-e04a-11e9-918c-d41b282e7ff0.png)

**Comment by kerimsari** [comment]
Could that be related with pg_hba.conf file as in this post

https://gis.stackexchange.com/questions/157931/osm2pgsql-failed-due-to-error-when-i-try-to-import-data-into-postgresql

**Comment by kerimsari** [comment]
I don't get a such error when i use Docker for Mac.
Previously i had Docker Toolbox.
When I switched to Docker for Mac i don't get the error

**Comment by Overv** [comment]
Please open a new issue as this has nothing to do with connecting to Postgres.
