### ISSUE TITLE
carto, stylesheet compiler warnings

### ISSUE THREAD

**Issue by stevo01** [Overv/openstreetmap-tile-server#70]
The output of command "carto project.mml > mapnik.xml" shows a lot of critical warnings which looks like following line:
`Warning: amenity-points.mss:2300:8 Styles do not match layer selector .text-low-zoom.`

There seems to be dependencies between mapnik, stylesheet and stylesheet compiler version. 
I found [article ](https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/#installation-procedure-suggested-by-openstreetmap-carto) which recomments the usage of carto version 0.18.2 instead newer versions.

I checked the current used version in docker container with following command:
`carto -v 
1.1.0`

After a downgrade to version 0.18.2 the warning are not shown any more.

The following command install version 0.18.2
`npm install -g carto@0.18.2`

I assume this adaptation solves the following issue: https://github.com/Overv/openstreetmap-tile-server/issues/5

**Comment by stevo01** [comment]
I made a test with import of planet file and usage of carto version 0.18.2 and openstreetmap-carto tag v4.23.0 and the result looks fine for me. Additional I added pull request https://github.com/Overv/openstreetmap-tile-server/pull/73 for usage of openstreetmap-carto tag v4.23.0 (latest tag at the moment) version instead ti use the master.

**Comment by Overv** [comment]
Nice, thanks for confirming!
