### ISSUE TITLE
"service postgresql stop" seems not to be used if docker container is stopped

### ISSUE THREAD

**Issue by stevo01** [Overv/openstreetmap-tile-server#75]
the commit https://github.com/Overv/openstreetmap-tile-server/commit/e37c31d2f0556f950db23f909d62b18cd3e60005 added a call of "service postgresql stop" in run.sh. 
After some tests, I observed, that "service postgresql stop" is not called, if you stop the container with "docker stop ..." command.

**Comment by Overv** [comment]
Fixed in 6e5f4f485da27a0c907529d8a7e9ebaf662d5799.
