### ISSUE TITLE
Failure to run command does not stop command

### ISSUE THREAD

**Issue by caiquecastro** [Overv/openstreetmap-tile-server#78]
When running the import command, the following command fails on my server:

https://github.com/Overv/openstreetmap-tile-server/blob/master/run.sh#L51

Is it an issue? I'm importing the tiles from Brazil. After the process is completed, it's the only error I got and when I run the server, the tiles return 404.

**Comment by caiquecastro** [comment]
The command seems to be requesting the http version instead of https. When I visit on the browser, it redirects to https.

**Comment by stevo01** [comment]
the command "openstreetmap-tiles-update-expire" is a shell script: https://github.com/Overv/openstreetmap-tile-server/blob/master/openstreetmap-tiles-update-expire#L111 

Can you add some details what failed during import? Is the file "/var/lib/mod_tile/replication_timestamp.txt" available? If yes: whats the content of the file?

**Comment by caiquecastro** [comment]
cat /var/lib/mod_tile/replication_timestamp.txt
2019-10-06

**Comment by caiquecastro** [comment]
When I run the following command from the docker host:
curl http://replicate-sequences.osm.mazdermind.de/?2019-10-06T00:00:00Z
curl: (7) Failed to connect to replicate-sequences.osm.mazdermind.de port 80: No route to host

But when I do: curl https://replicate-sequences.osm.mazdermind.de/?2019-10-06T00:00:00Z
I get:
#original-source: http://planet.openstreetmap.org/replication/minute/003/702/183.state.txt
#generated-by: https://replicate-sequences.osm.mazdermind.de/?2019-10-06T00:00:00Z
#Sat Oct 05 23:59:02 UTC 2019
sequenceNumber=3702183
txnMaxQueried=2346591060
txnActiveList=
txnReadyList=
txnMax=2346591060
timestamp=2019-10-05T23\:59\:01Z

**Comment by stevo01** [comment]
> When I run the following command from the docker host:
> curl http://replicate-sequences.osm.mazdermind.de/?2019-10-06T00:00:00Z
> curl: (7) Failed to connect to replicate-sequences.osm.mazdermind.de port 80: No route to host

Maybe an issue with your network setup? My test shows following results:
```
curl http://replicate-sequences.osm.mazdermind.de/?2019-10-06T00:00:00Z
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://replicate-sequences.osm.mazdermind.de/?2019-10-06T00:00:00Z">here</a>.</p>
</body></html>
```
curl with option -L:
```
root@stone:/tmp# curl -L http://replicate-sequences.osm.mazdermind.de/?2019-10-06T00:00:00Z
#original-source: http://planet.openstreetmap.org/replication/minute/003/702/183.state.txt
#generated-by: https://replicate-sequences.osm.mazdermind.de/?2019-10-06T00:00:00Z
#Sat Oct 05 23:59:02 UTC 2019
sequenceNumber=3702183
txnMaxQueried=2346591060
txnActiveList=
txnReadyList=
txnMax=2346591060
timestamp=2019-10-05T23\:59\:01Z
```
and wget (method from shell script)
```
root@stone:/tmp# cat state.txt
cat: state.txt: No such file or directory
root@stone:/tmp# wget "http://replicate-sequences.osm.mazdermind.de/?"2019-10-06"T00:00:00Z" -O state.txt
URL transformed to HTTPS due to an HSTS policy
--2019-10-08 14:38:11--  https://replicate-sequences.osm.mazdermind.de/?2019-10-06T00:00:00Z
Resolving replicate-sequences.osm.mazdermind.de (replicate-sequences.osm.mazdermind.de)... 188.68.50.52, 2a03:4000:6:d080::1
Connecting to replicate-sequences.osm.mazdermind.de (replicate-sequences.osm.mazdermind.de)|188.68.50.52|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 332 [text/plain]
Saving to: ‘state.txt’

state.txt                         100%[=============================================================>]     332  --.-KB/s    in 0s

2019-10-08 14:38:12 (6.70 MB/s) - ‘state.txt’ saved [332/332]

root@stone:/tmp# cat state.txt
#original-source: http://planet.openstreetmap.org/replication/minute/003/702/183.state.txt
#generated-by: https://replicate-sequences.osm.mazdermind.de/?2019-10-06T00:00:00Z
#Sat Oct 05 23:59:02 UTC 2019
sequenceNumber=3702183
txnMaxQueried=2346591060
txnActiveList=
txnReadyList=
txnMax=2346591060
timestamp=2019-10-05T23\:59\:01Z
```
From my point of view it works like expected. 

Anyway: We should change to the url with "https" method.

**Comment by caiquecastro** [comment]
I checked. I'm only having this network issue on my network (behind a corporate proxy). I asked for support from the my company's infrastructure team.
