### ISSUE TITLE
Provide Multiple Styles & Upgrade to Postgresql 12

### ISSUE THREAD

**Issue by Y0ngg4n** [Overv/openstreetmap-tile-server#79]
**Multiple Styles:**
Is it possible to provide multiple Styles?
I found [this](https://gis.stackexchange.com/questions/79077/serving-multiple-styles-from-tile-server)

But maybe there is an option to do this without forking your repository?
Maybe with multiple volume bindings?

**Upgrade Postgresql:**
Is it possible that you upgrade your postgresql version to 12?

**Comment by Overv** [comment]
>But maybe there is an option to do this without forking your repository?
>Maybe with multiple volume bindings?

I think that adding support for multiple styles will be a bit complicated, but maybe others can weigh in here.

>Is it possible that you upgrade your postgresql version to 12?

Yes. Mainly to just take advantage of performance improvements or is there more you'd like to get out of it?

**Comment by Y0ngg4n** [comment]
@Overv Ok should i try to implement it and make a pull request then?

Just performance.

**Comment by Overv** [comment]
Yes, please.

**Comment by Y0ngg4n** [comment]
@Overv Could you please give me the right to push to a new branch? I have finished the postgresql 12 update and wanted to push it to a new branch but didn´t have the rights for.

**Comment by Istador** [comment]
Usually on Github that is done by forking the repository.
You can create as many branches and changes to master as you like in your fork.
When you are done with it, you create a pull request and say which branch of your fork should be merged.
After your fork is merged you can delete your fork. Github even offers a convenient button for that.

**Comment by Y0ngg4n** [comment]
@Istador created a Pull Request for Upgrade to Postgresql 12:
[81](https://github.com/Overv/openstreetmap-tile-server/pull/81)

**Comment by Jezternz** [comment]
May or may not be useful and can be tweaked, but I have created a multi-style example here: 
https://github.com/Jezternz/openstreetmap-tile-server-vizall

**Comment by Y0ngg4n** [comment]
@Jezternz Thx ;) Can you merge it into this Repository or is ist not modular?

**Comment by Jezternz** [comment]
@Y0ngg4n its not really in a place to nicely be merged in, Unfortunately I am quite time strapped, otherwise I would gladly get it merged - Maybe down the track when I have a bit more time.

**Comment by Y0ngg4n** [comment]
@Jezternz ok i will close this issue, hoping you merge it if you have time.
