### ISSUE TITLE
Update readme at dockerhub

### ISSUE THREAD

**Issue by gjedeer** [Overv/openstreetmap-tile-server#84]
I've been following the instructons from https://hub.docker.com/r/overv/openstreetmap-tile-server and was wondering why my import has been lost. It was because the readme command line examples were referring to Postgres 10 while the Dockerfile is already using 12.

**Comment by Overv** [comment]
I've updated the README to the latest version. Sorry for your troubles.

**Comment by gjedeer** [comment]
Thank you for the great Docker image! ✌️
