### ISSUE TITLE
unable to find user root: no matching entries in passwd

### ISSUE THREAD

**Issue by gareth-johnstone** [Overv/openstreetmap-tile-server#87]
Hi Guys,
I appear to be having a new issue - i've got myself a much more powerful server, set everything up the way i have done in the past and now i appear to be getting this when ever i run

```
docker run \
-e UPDATES=enabled \
-v /home/osm/great-britain-latest.osm.pbf:/data.osm.pbf \
-v /home/osm/great-britain.poly:/data.poly \
-v openstreetmap-data:/var/lib/postgresql/12/main \
-v openstreetmap-rendered-tiles \
overv/openstreetmap-tile-server \
import
```

```
docker: Error response from daemon: unable to find user root: no matching entries in passwd file.
ERRO[0000] error waiting for container: context canceled
```

Any ideas? - Googling this problem - loads of others appear to have an issue similar but no one has a fix.

**Comment by Overv** [comment]
I'm closing this as this sounds like a general issue with Docker rather than a problem with this particular image.
