### ISSUE TITLE
Consider using conf.d for postgresql.custom.conf

### ISSUE THREAD

**Issue by mfotzler** [Overv/openstreetmap-tile-server#89]
Hello,

We wanted to override and add some settings to the postgresql.custom.conf file. We noticed that the way the dockerfile is setup now, it adds an explicit include statement for it at the end of the postgres.conf file (which is after the include_dir conf.d statement).

This means we can't simply add a file to conf.d to override postgresql.custom.conf, since it's included at the very end. It would be great in this scenario if it was instead something like `conf.d/10-postgresql.custom.conf`

We made a workaround for this case, but using conf.d for the custom conf file would make these overrides easier.

Matt

**Comment by Overv** [comment]
Good idea, fixed in version v1.3.9.
