### ISSUE TITLE
Error response from daemon: invalid mode: /data.osm.pbf.

### ISSUE THREAD

**Issue by beknazar** [Overv/openstreetmap-tile-server#9]
Hello,

When I am trying to create the server in this way:

`docker run -v https://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf:/data.osm.pbf -v openstreetmap-data:/var/lib/postgresql/10/main overv/openstreetmap-tile-server import`

Getting the following error:
`docker: Error response from daemon: invalid mode: /data.osm.pbf.`

**Comment by Istador** [comment]
You have to download the file first. The `-v` (`--volume`) option of [docker run](https://docs.docker.com/engine/reference/commandline/run/)  does not work with URLs afaik.

**Comment by beknazar** [comment]
Thank you, i fixed as explained.

**Comment by beknazar** [comment]
Thank you, i fixed as explained.

**Comment by beknazar** [comment]
Thank you, i fixed as explained.
