### ISSUE TITLE
QGis Connection

### ISSUE THREAD

**Issue by asitemade4u** [Overv/openstreetmap-tile-server#91]
Thanks to your excellent documentation, I was able to:

- set up the tile server using a custom hostname
- import the pbf file
- publish the tiles and access them in the Web browser from <hostname>
- in QGis, access the **vector** part of the OSM file

BUT, I could not find a way to access the **raster** part of the OSM file, aka the tiles themselves.

I tried to connect with `<hostname>/{z}/{x}/{y}.png` as in a standard WMS server but it did not work.
Can you help please and, perhaps, add the connection settings to the documentation?

**Comment by Overv** [comment]
The URL is `http://<hostname>/tile/{z}/{x}/{y}.png`.

**Comment by asitemade4u** [comment]
Thank you so much for your quick response.
