### ISSUE TITLE
Using docker-compose instead of a script

### ISSUE THREAD

**Issue by asitemade4u** [Overv/openstreetmap-tile-server#92]
As I am using Dockstation to manage my Docker projects and Traefik to allow them to cohabitate, I would prefer using a `docker-compose.yaml` file to launch the tile server.
I am puzzled however, in the run script, by the call to `run` twice: once to launch the building of the container, once to execute the server itself.
I have no idea on how to translate that second `run` call in a docker-compose file.
Please help.
Best,
Stephen

**Comment by kutensky** [comment]
There is an example of docker-compose.yml file in the repository. Check it out
