### ISSUE TITLE
[Question] What determines tile expiry and when does it re-render?

### ISSUE THREAD

**Issue by gareth-johnstone** [Overv/openstreetmap-tile-server#93]
Hi Guys,
I've actually managed to get this running! (so thanks for all your help so far!)

Anyways, I have enabled auto updates (on import and when running the server)

I rendered an area on the map and made an edit on openstreetmap.org (a legit edit) I can see the edit if i zoom in to level 20 but if i zoom out to a zoom level thats been rendered already it doesnt (obviously)

So what determines that tile to expire and when should i expect it to re-render with the correction?

**Comment by stevo01** [comment]
I had same questions and found more or less no documentation (in mod_tile, renderd project) about this topic. 

My current assumtions:

I) osm2psql returns a list with expired tiles if you use it with option -a (append) The file is defined here: https://github.com/Overv/openstreetmap-tile-server/blob/010f87d71171638f81f18d892f0774643ae3bdeb/openstreetmap-tiles-update-expire#L44
The update scripts includes additional some definitions which defines expiry zoom levels 
https://github.com/Overv/openstreetmap-tile-server/blob/010f87d71171638f81f18d892f0774643ae3bdeb/openstreetmap-tiles-update-expire#L60
and
https://github.com/Overv/openstreetmap-tile-server/blob/010f87d71171638f81f18d892f0774643ae3bdeb/openstreetmap-tiles-update-expire#L63

II) render_expired get the list with expired tiles and mark the tiles as expired (inside the tile cache)
https://github.com/Overv/openstreetmap-tile-server/blob/010f87d71171638f81f18d892f0774643ae3bdeb/openstreetmap-tiles-update-expire#L189

III) The web server (apache+mod_tile plugin) check if tile is available in tile cache after a request from web browser. If the tile is available but marked as expired, the web server request renderd to render the tile again. If renderd is busy or needs to long time to render the tile, the webserver delivers the "expired" tile from cache to web browser. This behavior can be configured with parameter ModTileRequestTimeout in apache configuration.
https://github.com/Overv/openstreetmap-tile-server/blob/010f87d71171638f81f18d892f0774643ae3bdeb/apache.conf#L6

note: There is a document with description about the 
[Tirex/Tile Update Strategies](https://wiki.openstreetmap.org/wiki/Tirex/Tile_Update_Strategies) available for tirex.

**Comment by stevo01** [comment]
Hi,
> So what determines that tile to expire and when should i expect it to re-render with the correction?

another explanation:
You need to remove the cache of your web server to avoid that web browser shows you tiles from your local cache.

**Comment by stevo01** [comment]
> Hi Guys,
> I've actually managed to get this running! (so thanks for all your help so far!)

Are you working with whole osm planet or extract of planet?

**Comment by miqueet** [comment]
from what i can tell renderd apache2 config file appears to expire cached tiles based on a timeout.
