### ISSUE TITLE
PostgreSQL: directory is not a database cluster directory

### ISSUE THREAD

**Issue by Derkades** [Overv/openstreetmap-tile-server#94]
When running
```
docker run -v /tank/maps/data.osm.pbf:/data.osm.pbf -v /tank/maps/data:/var/lib/postgresql/12/main overv/openstreetmap-tile-server import
```
I get
```
+ service postgresql start
 * Starting PostgreSQL 12 database server
 * Error: /usr/lib/postgresql/12/bin/pg_ctl /usr/lib/postgresql/12/bin/pg_ctl start -D /var/lib/postgresql/12/main -l /var/log/postgresql/postgresql-12-main.log -s -o  -c config_file="/etc/postgresql/12/main/postgresql.conf"  exited with status 1:
pg_ctl: directory "/var/lib/postgresql/12/main" is not a database cluster directory
[.. everything failing because postgresql is down]
```
and indeed, the data folder is empty. Why?

**Comment by Overv** [comment]
This is probably happening because the directory you mount into the container has the wrong permissions for Postgres. If you want to map a host directory like this then you should assign the right user/group to it.

**Comment by Derkades** [comment]
Thanks! I was able to find the ID using instructions from https://stackoverflow.com/a/39329138/4833737 . In case anyone needs it in the future, the values for me were:
* UID: 102
* GID: 105

I still was not able to run the container though, I am getting the same error and the directory is empty.

**Comment by Overv** [comment]
I'm not able to exactly reproduce the error on my machine, though. For me the output is more like:

```
+ service postgresql start
 * Starting PostgreSQL 12 database server                                                                                                                                              * Error: The cluster is owned by group id 985 which does not exist
```

I don't get the error about it not being a database cluster directory like you do. What kind of operating system are you running on and are you 100% sure the directory is completely empty (no hidden files)?

**Comment by Derkades** [comment]
```
[... earlier output of the docker run command ... ]
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
+ touch /var/lib/mod_tile/planet-import-complete
+ service postgresql stop
 * Stopping PostgreSQL 12 database server
   ...done.
+ exit 0
root@server:/srv# ls -al /tank/maps/data
total 13
drwxr-xr-x 2 syslog crontab         2 Dec 12 22:16 .
drwxr-xr-x 5 syslog systemd-network 6 Dec 12 22:03 ..
```
syslog is uid 102, crontab is gid 105

I am using Ubuntu 19.10 (upgraded from 18.04)

**Comment by Overv** [comment]
What kind of file system/volume is /tank?

**Comment by Derkades** [comment]
It is a ZFS dataset

**Comment by Overv** [comment]
In that case I don't know why this would happen.

**Comment by Derkades** [comment]
I know you're not docker support so sorry to bother you with this but when do docker containers (or specifically this container) decide to populate directories with files? Is it like APT, where there is a "setup" stage where all files are generated, or are they generated at every startup if they do not exist?

I guess I am just doing something fundamentally wrong with docker. There are some other docker containers that I can't get working as well due to similar issues. They're complaining about missing files or invalid permissions even when the directory permissions are set to 777. These containers all do work and create files when I don't add any volumes, but as soon as I map volumes in the container the directories stay empty.

There are 41 docker containers in my docker compose file at the moment, of which a few have this issue (`overv/openstreetmap-tile-server`, `mozilla/syncserver`, `libreoffice/online`, `d0u9/youtube-dl-webui`)

**Comment by Xoppop** [comment]
> 
> 
> I know you're not docker support so sorry to bother you with this but when do docker containers (or specifically this container) decide to populate directories with files? Is it like APT, where there is a "setup" stage where all files are generated, or are they generated at every startup if they do not exist? If it is in the "setup" phase, aren't docker images only "built" once during docker pull, where it doesn't have any knowledge of volumes yet?
> 
> I guess I am just doing something fundamentally wrong with docker. There are some other docker containers that I can't get working as well due to similar issues. They're complaining about missing files or invalid permissions even when the directory permissions are set to 777. These containers all do work and create files when I don't add any volumes, but as soon as I map volumes in the container the directories stay empty.
> 
> There are 41 docker containers in my docker compose file at the moment, of which a few have this issue (`overv/openstreetmap-tile-server`, `mozilla/syncserver`, `libreoffice/online`, `d0u9/youtube-dl-webui`)
Same problem. We found a solution?

**Comment by Derkades** [comment]
No, I gave up getting this to work for now.

**Comment by Derkades** [comment]
Should PostgreSQL even be in this container? Docker recommends keeping it to one process per container. In this case it would probably be better to have an external PostgreSQL container.

**Comment by bhdzllr** [comment]
I had the same probleme and did the following:

`docker volume create --name openstreetmap-data --opt type=none --opt o=bind --opt device=/path/to/volume`

Then start the import with the name of the volume not the path.

I'm trying to import Europe, and now get another error:

`Osm2pgsql failed due to ERROR: failed to uncompress data: buffer error`

**Comment by tabrms** [comment]
Guys, if you've got here because you're using Docker and you've actually mounted `/var/lib/postgresql/12/main` to your empty host directory, here's what you need to do

Run container interactively with entrypoint override to bash `docker run -ti --rm --entrypoint bash -v /path/to/host/directory:/var/lib/postgresql/12/main overv/openstreetmap-tile-server`

Launch second SSH session and get container ID `docker ps -a`

Use this container ID (let's assume it's 123) to copy content of /var/lib/postgresql/12/main to you host `docker cp 123:/var/lib/postgresql/12/main /path/to/host/directory`

Change owner and group recursively
```
chown -R 102 /path/to/host/directory
chgrp -R 105 /path/to/host/directory
```

Then start the container again and now it works as expected.

**Comment by sneak** [comment]
@tabrms you have to leave the `-v` out of the bash override run, so it gets populated.

```
docker run -ti --name pgsourcefiles --rm --entrypoint bash overv/openstreetmap-tile-server
```

...then, in another window/pane...

```
docker cp pgsourcefiles:/var/lib/postgresql/12/main/ /tmp/pgmain/
mv /tmp/pgmain/* /path/to/host/directory
chown -R 102:105 /path/to/host/directory
```

**Comment by NightDragon1** [comment]
Solution for me: I used a block device, mounted as directory on the host. It was using ext4. So there was a lost+found folder. It produces exactly the above message. After deleting the lost+found folder, all went fine.
